In [1]:
#File manipulation
import os
from datetime import datetime

#Data manipulation
import requests
import numpy as np
import pandas as pd
import geopandas as gpd
import seaborn as sns
from shapely.geometry import Polygon

#Visualisation
import matplotlib.pyplot as plt
import branca.colormap as cm
import folium
from folium.plugins import MarkerCluster

# 2.1 api microclimate sensor readings

https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/microclimate-sensor-readings/records?limit=10&offset=0&timezone=UTC&include_links=

In [83]:
BASE_URL = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/'

#Dataset name
SENSOR_DATASET = 'microclimate-sensor-readings'
NUMBER_OF_RECORDS = 10

# Add a filter for the number of results returned
FILTERS = f'records?limit={NUMBER_OF_RECORDS}&offset=0&timezone=UTC'

In [84]:
SENSOR_URL = f'{BASE_URL}{SENSOR_DATASET}/{FILTERS}'
SENSOR_URL

'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/microclimate-sensor-readings/records?limit=10&offset=0&timezone=UTC'

In [85]:
# Use requests to get the data
result = requests.get(SENSOR_URL)

In [86]:
result

In [87]:
result.text

'{"total_count": 1340, "results": [{"local_time": "2023-07-26T14:15:02+00:00", "id": 7595165, "site_id": 1014, "sensor_id": "5b", "value": 80.14, "type": "TPH.RH", "units": "%", "gatewayhub_id": "arc1045", "site_status": "C"}, {"local_time": "2023-07-26T14:15:05+00:00", "id": 7595073, "site_id": 1011, "sensor_id": "5b", "value": 75.54, "type": "TPH.RH", "units": "%", "gatewayhub_id": "arc1055", "site_status": "C"}, {"local_time": "2023-07-26T14:15:05+00:00", "id": 7595078, "site_id": 1011, "sensor_id": "5c", "value": 1028.8, "type": "TPH.PRESSURE", "units": "hPa", "gatewayhub_id": "arc1055", "site_status": "C"}, {"local_time": "2023-07-26T14:15:05+00:00", "id": 7595112, "site_id": 1012, "sensor_id": "5a", "value": 8.72, "type": "TPH.TEMP", "units": "C", "gatewayhub_id": "arc1048", "site_status": "C"}, {"local_time": "2023-07-26T14:15:07+00:00", "id": 7595204, "site_id": 1016, "sensor_id": "5a", "value": 9.35, "type": "TPH.TEMP", "units": "C", "gatewayhub_id": "arc1049", "site_status": "C"}, {"local_time": "2023-07-26T14:15:07+00:00", "id": 7595214, "site_id": 1016, "sensor_id": "5c", "value": 1029.2, "type": "TPH.PRESSURE", "units": "hPa", "gatewayhub_id": "arc1049", "site_status": "C"}, {"local_time": "2023-07-26T14:15:10+00:00", "id": 7595022, "site_id": 1009, "sensor_id": "0a", "value": 8.8, "type": "PM2.5", "units": "ug/m^3", "gatewayhub_id": "arc1050", "site_status": "C"}, {"local_time": "2023-07-26T14:15:11+00:00", "id": 7595139, "site_id": 1014, "sensor_id": "0b", "value": 26.6, "type": "PM10", "units": "ug/m^3", "gatewayhub_id": "arc1045", "site_status": "C"}, {"local_time": "2023-07-26T14:15:16+00:00", "id": 7595178, "site_id": 1016, "sensor_id": "0a", "value": 13.0, "type": "PM2.5", "units": "ug/m^3", "gatewayhub_id": "arc1049", "site_status": "C"}, {"local_time": "2023-07-26T14:15:16+00:00", "id": 7595187, "site_id": 1016, "sensor_id": "0b", "value": 40.9, "type": "PM10", "units": "ug/m^3", "gatewayhub_id": "arc1049", "site_status": "C"}]}'

In [88]:
result.json()

{'total_count': 1340,
 'results': [{'local_time': '2023-07-26T14:15:02+00:00',
   'id': 7595165,
   'site_id': 1014,
   'sensor_id': '5b',
   'value': 80.14,
   'type': 'TPH.RH',
   'units': '%',
   'gatewayhub_id': 'arc1045',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:05+00:00',
   'id': 7595073,
   'site_id': 1011,
   'sensor_id': '5b',
   'value': 75.54,
   'type': 'TPH.RH',
   'units': '%',
   'gatewayhub_id': 'arc1055',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:05+00:00',
   'id': 7595078,
   'site_id': 1011,
   'sensor_id': '5c',
   'value': 1028.8,
   'type': 'TPH.PRESSURE',
   'units': 'hPa',
   'gatewayhub_id': 'arc1055',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:05+00:00',
   'id': 7595112,
   'site_id': 1012,
   'sensor_id': '5a',
   'value': 8.72,
   'type': 'TPH.TEMP',
   'units': 'C',
   'gatewayhub_id': 'arc1048',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:07+00:00',
   'id': 7595204,
   'site_id': 1016,
   'sensor_id': '5a',
   'value': 9.35,
   'type': 'TPH.TEMP',
   'units': 'C',
   'gatewayhub_id': 'arc1049',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:07+00:00',
   'id': 7595214,
   'site_id': 1016,
   'sensor_id': '5c',
   'value': 1029.2,
   'type': 'TPH.PRESSURE',
   'units': 'hPa',
   'gatewayhub_id': 'arc1049',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:10+00:00',
   'id': 7595022,
   'site_id': 1009,
   'sensor_id': '0a',
   'value': 8.8,
   'type': 'PM2.5',
   'units': 'ug/m^3',
   'gatewayhub_id': 'arc1050',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:11+00:00',
   'id': 7595139,
   'site_id': 1014,
   'sensor_id': '0b',
   'value': 26.6,
   'type': 'PM10',
   'units': 'ug/m^3',
   'gatewayhub_id': 'arc1045',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:16+00:00',
   'id': 7595178,
   'site_id': 1016,
   'sensor_id': '0a',
   'value': 13.0,
   'type': 'PM2.5',
   'units': 'ug/m^3',
   'gatewayhub_id': 'arc1049',
   'site_status': 'C'},
  {'local_time': '2023-07-26T14:15:16+00:00',
   'id': 7595187,
   'site_id': 1016,
   'sensor_id': '0b',
   'value': 40.9,
   'type': 'PM10',
   'units': 'ug/m^3',
   'gatewayhub_id': 'arc1049',
   'site_status': 'C'}]}

In [8]:
result_json = result.json()

In [9]:
result_json = result.json()

In [10]:
result_json.keys()

dict_keys(['total_count', 'results'])

In [11]:
result_json['total_count']

1340

In [12]:
result_json['results']

[{'local_time': '2023-07-26T14:15:02+00:00',
  'id': 7595165,
  'site_id': 1014,
  'sensor_id': '5b',
  'value': 80.14,
  'type': 'TPH.RH',
  'units': '%',
  'gatewayhub_id': 'arc1045',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:05+00:00',
  'id': 7595073,
  'site_id': 1011,
  'sensor_id': '5b',
  'value': 75.54,
  'type': 'TPH.RH',
  'units': '%',
  'gatewayhub_id': 'arc1055',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:05+00:00',
  'id': 7595078,
  'site_id': 1011,
  'sensor_id': '5c',
  'value': 1028.8,
  'type': 'TPH.PRESSURE',
  'units': 'hPa',
  'gatewayhub_id': 'arc1055',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:05+00:00',
  'id': 7595112,
  'site_id': 1012,
  'sensor_id': '5a',
  'value': 8.72,
  'type': 'TPH.TEMP',
  'units': 'C',
  'gatewayhub_id': 'arc1048',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:07+00:00',
  'id': 7595204,
  'site_id': 1016,
  'sensor_id': '5a',
  'value': 9.35,
  'type': 'TPH.TEMP',
  'units': 'C',
  'gatewayhub_id': 'arc1049',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:07+00:00',
  'id': 7595214,
  'site_id': 1016,
  'sensor_id': '5c',
  'value': 1029.2,
  'type': 'TPH.PRESSURE',
  'units': 'hPa',
  'gatewayhub_id': 'arc1049',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:10+00:00',
  'id': 7595022,
  'site_id': 1009,
  'sensor_id': '0a',
  'value': 8.8,
  'type': 'PM2.5',
  'units': 'ug/m^3',
  'gatewayhub_id': 'arc1050',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:11+00:00',
  'id': 7595139,
  'site_id': 1014,
  'sensor_id': '0b',
  'value': 26.6,
  'type': 'PM10',
  'units': 'ug/m^3',
  'gatewayhub_id': 'arc1045',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:16+00:00',
  'id': 7595178,
  'site_id': 1016,
  'sensor_id': '0a',
  'value': 13.0,
  'type': 'PM2.5',
  'units': 'ug/m^3',
  'gatewayhub_id': 'arc1049',
  'site_status': 'C'},
 {'local_time': '2023-07-26T14:15:16+00:00',
  'id': 7595187,
  'site_id': 1016,
  'sensor_id': '0b',
  'value': 40.9,
  'type': 'PM10',
  'units': 'ug/m^3',
  'gatewayhub_id': 'arc1049',
  'site_status': 'C'}]

In [13]:
results = result_json['results']

In [14]:
len(results)

10

In [15]:
for i in results[:5]:
    print(i)

{'local_time': '2023-07-26T14:15:02+00:00', 'id': 7595165, 'site_id': 1014, 'sensor_id': '5b', 'value': 80.14, 'type': 'TPH.RH', 'units': '%', 'gatewayhub_id': 'arc1045', 'site_status': 'C'}
{'local_time': '2023-07-26T14:15:05+00:00', 'id': 7595073, 'site_id': 1011, 'sensor_id': '5b', 'value': 75.54, 'type': 'TPH.RH', 'units': '%', 'gatewayhub_id': 'arc1055', 'site_status': 'C'}
{'local_time': '2023-07-26T14:15:05+00:00', 'id': 7595078, 'site_id': 1011, 'sensor_id': '5c', 'value': 1028.8, 'type': 'TPH.PRESSURE', 'units': 'hPa', 'gatewayhub_id': 'arc1055', 'site_status': 'C'}
{'local_time': '2023-07-26T14:15:05+00:00', 'id': 7595112, 'site_id': 1012, 'sensor_id': '5a', 'value': 8.72, 'type': 'TPH.TEMP', 'units': 'C', 'gatewayhub_id': 'arc1048', 'site_status': 'C'}
{'local_time': '2023-07-26T14:15:07+00:00', 'id': 7595204, 'site_id': 1016, 'sensor_id': '5a', 'value': 9.35, 'type': 'TPH.TEMP', 'units': 'C', 'gatewayhub_id': 'arc1049', 'site_status': 'C'}

In [16]:
pm10_df = pd.json_normalize(results)

In [17]:
pm10_df

,local_time,id,site_id,sensor_id,value,type,units,gatewayhub_id,site_status
0,2023-07-26T14:15:02+00:00,7595165,1014,5b,80.14,TPH.RH,%,arc1045,C
1,2023-07-26T14:15:05+00:00,7595073,1011,5b,75.54,TPH.RH,%,arc1055,C
2,2023-07-26T14:15:05+00:00,7595078,1011,5c,1028.80,TPH.PRESSURE,hPa,arc1055,C
3,2023-07-26T14:15:05+00:00,7595112,1012,5a,8.72,TPH.TEMP,C,arc1048,C
4,2023-07-26T14:15:07+00:00,7595204,1016,5a,9.35,TPH.TEMP,C,arc1049,C
5,2023-07-26T14:15:07+00:00,7595214,1016,5c,1029.20,TPH.PRESSURE,hPa,arc1049,C
6,2023-07-26T14:15:10+00:00,7595022,1009,0a,8.80,PM2.5,ug/m^3,arc1050,C
7,2023-07-26T14:15:11+00:00,7595139,1014,0b,26.60,PM10,ug/m^3,arc1045,C
8,2023-07-26T14:15:16+00:00,7595178,1016,0a,13.00,PM2.5,ug/m^3,arc1049,C
9,2023-07-26T14:15:16+00:00,7595187,1016,0b,40.90,PM10,ug/m^3,arc1049,C

In [18]:
pm10_df.shape

(10, 9)

In [19]:
pm10_df[['id', 'site_id']] = pm10_df[['id', 'site_id']].astype(int)
pm10_df[['value']] = pm10_df[['value']].astype(float)
pm10_df['local_time'] = pd.to_datetime(pm10_df['local_time'] )
pm10_df = pm10_df.convert_dtypes()

pm10_df.dtypes

local_time       datetime64[ns, UTC]
id                             Int32
site_id                        Int32
sensor_id                     string
value                        Float64
type                          string
units                         string
gatewayhub_id                 string
site_status                   string
dtype: object

In [20]:
groupbyfields = ['site_id']
aggregatebyfields = ["count", "mean"]

# Create new DataFrame with value counts and mean values for each site.
pm10SiteCount = pd.DataFrame(pm10_df.groupby(groupbyfields, as_index=False)['value'].agg(aggregatebyfields)
                             .add_prefix('value_'))
pm10SiteCount = pm10SiteCount.reset_index()
pm10SiteCount

   site_id  value_count  value_mean
0     1009            1         8.8
1     1011            2      552.17
2     1012            1        8.72
3     1014            2       53.37
4     1016            4    273.1125

In [21]:
pm10_df

,local_time,id,site_id,sensor_id,value,type,units,gatewayhub_id,site_status
0,2023-07-26 14:15:02+00:00,7595165,1014,5b,80.14,TPH.RH,%,arc1045,C
1,2023-07-26 14:15:05+00:00,7595073,1011,5b,75.54,TPH.RH,%,arc1055,C
2,2023-07-26 14:15:05+00:00,7595078,1011,5c,1028.8,TPH.PRESSURE,hPa,arc1055,C
3,2023-07-26 14:15:05+00:00,7595112,1012,5a,8.72,TPH.TEMP,C,arc1048,C
4,2023-07-26 14:15:07+00:00,7595204,1016,5a,9.35,TPH.TEMP,C,arc1049,C
5,2023-07-26 14:15:07+00:00,7595214,1016,5c,1029.2,TPH.PRESSURE,hPa,arc1049,C
6,2023-07-26 14:15:10+00:00,7595022,1009,0a,8.8,PM2.5,ug/m^3,arc1050,C
7,2023-07-26 14:15:11+00:00,7595139,1014,0b,26.6,PM10,ug/m^3,arc1045,C
8,2023-07-26 14:15:16+00:00,7595178,1016,0a,13.0,PM2.5,ug/m^3,arc1049,C
9,2023-07-26 14:15:16+00:00,7595187,1016,0b,40.9,PM10,ug/m^3,arc1049,C

In [22]:
pm10_df['site_id'].unique()

<IntegerArray>
[1014, 1011, 1012, 1016, 1009]
Length: 5, dtype: Int32

# reading microclimate sensor reading data from csv file

In [68]:
df = pd.read_csv('data.csv')

In [69]:
df

,Local_Time,ID,Site_ID,Sensor_ID,Value,Type,Units,Gatewayhub_ID,Site_Status
0,2023-07-27T00:15:02+10:00,7595165,1014,5b,80.14,TPH.RH,%,arc1045,C
1,2023-07-27T00:15:05+10:00,7595073,1011,5b,75.54,TPH.RH,%,arc1055,C
2,2023-07-27T00:15:05+10:00,7595078,1011,5c,1028.80,TPH.PRESSURE,hPa,arc1055,C
3,2023-07-27T00:15:05+10:00,7595112,1012,5a,8.72,TPH.TEMP,C,arc1048,C
4,2023-07-27T00:15:07+10:00,7595204,1016,5a,9.35,TPH.TEMP,C,arc1049,C
...,...,...,...,...,...,...,...,...,...
1335,2023-07-27T09:00:02+10:00,7596665,1011,5a,9.33,TPH.TEMP,C,arc1055,C
1336,2023-07-27T09:00:02+10:00,7596670,1011,5b,75.80,TPH.RH,%,arc1055,C
1337,2023-07-27T09:00:02+10:00,7596767,1014,5c,1028.20,TPH.PRESSURE,hPa,arc1045,C
1338,2023-07-27T09:00:11+10:00,7596625,1009,0b,23.60,PM10,ug/m^3,arc1050,C
1339,2023-07-27T09:00:11+10:00,7596648,1011,0b,26.50,PM10,ug\/m^3,arc1055,C

In [70]:
df['Type'].unique()

array(['TPH.RH', 'TPH.PRESSURE', 'TPH.TEMP', 'PM2.5', 'PM10', 'WS',
       'PM2.5-EPA-1h', 'PM10-EPA-1h', 'PM10-EPA-1h-NOPK',
       'TPH.TEMP-EPA-1h', 'TPH.RH-EPA-1h', 'PM2.5-EPA-1h-PKIND',
       'PM10-EPA-1h-NOPK-EPA-24h', 'PM10-EPA-24h', 'PM10-EPA-1h-PKIND',
       'PM2.5-EPA-1h-NOPK-EPA-24h', 'PM2.5-EPA-24h', 'PM2.5-EPA-1h-NOPK'],
      dtype=object)

In [71]:
df['Site_ID'].unique()

array([1014, 1011, 1012, 1016, 1009], dtype=int64)

In [72]:
df.rename(columns = {'Local_Time':'local_time', 'ID':'id', 'Site_ID':'site_id', 'Value':'value', 'Type': 'type', 
                     'Units':'units', 'Gatewayhub_ID':'gatewayhub_id', 'Site_Status':'site_status'}, inplace = True)

In [74]:
df

,local_time,id,site_id,Sensor_ID,value,type,units,gatewayhub_id,site_status
0,2023-07-27T00:15:02+10:00,7595165,1014,5b,80.14,TPH.RH,%,arc1045,C
1,2023-07-27T00:15:05+10:00,7595073,1011,5b,75.54,TPH.RH,%,arc1055,C
2,2023-07-27T00:15:05+10:00,7595078,1011,5c,1028.80,TPH.PRESSURE,hPa,arc1055,C
3,2023-07-27T00:15:05+10:00,7595112,1012,5a,8.72,TPH.TEMP,C,arc1048,C
4,2023-07-27T00:15:07+10:00,7595204,1016,5a,9.35,TPH.TEMP,C,arc1049,C
...,...,...,...,...,...,...,...,...,...
1335,2023-07-27T09:00:02+10:00,7596665,1011,5a,9.33,TPH.TEMP,C,arc1055,C
1336,2023-07-27T09:00:02+10:00,7596670,1011,5b,75.80,TPH.RH,%,arc1055,C
1337,2023-07-27T09:00:02+10:00,7596767,1014,5c,1028.20,TPH.PRESSURE,hPa,arc1045,C
1338,2023-07-27T09:00:11+10:00,7596625,1009,0b,23.60,PM10,ug/m^3,arc1050,C
1339,2023-07-27T09:00:11+10:00,7596648,1011,0b,26.50,PM10,ug\/m^3,arc1055,C

In [75]:
df = df.loc[df['type'] == 'PM10-EPA-1h-NOPK-EPA-24h']

In [78]:
df.shape

(31, 9)

In [35]:
groupbyfields = ['site_id']
aggregatebyfields = ["count", "mean"]

# Create new DataFrame with value counts and mean values for each site.
pm10SiteCount = pd.DataFrame(df.groupby(groupbyfields, as_index=False)['value'].agg(aggregatebyfields)
                             .add_prefix('value_'))
pm10SiteCount = pm10SiteCount.reset_index()
pm10SiteCount

   site_id  value_count  value_mean
0     1009          104   19.781731
1     1011          312  142.189776
2     1012          312  141.654006
3     1014          300  147.640933
4     1016          312  141.301314

In [37]:
groupbyfields = ['site_id']
aggregatebyfields = {'local_time': ["min", "max"]}

# Create new DataFrame highlighting start and end dates.
recordingDates= pd.DataFrame(df.groupby(groupbyfields, as_index=False).agg(aggregatebyfields))
recordingDates

  site_id                 local_time
                                 min                        max
0    1009  2023-07-27T00:15:10+10:00  2023-07-27T09:00:11+10:00
1    1011  2023-07-27T00:15:05+10:00  2023-07-27T09:00:11+10:00
2    1012  2023-07-27T00:15:05+10:00  2023-07-27T09:00:11+10:00
3    1014  2023-07-27T00:15:02+10:00  2023-07-27T09:00:11+10:00
4    1016  2023-07-27T00:15:07+10:00  2023-07-27T09:00:11+10:00

In [80]:
groupbyfields = ['site_id', pd.Grouper(key='local_time', freq='M')]
aggregatebyfields = {'value':['mean']}

In [81]:
df

,local_time,id,site_id,Sensor_ID,value,type,units,gatewayhub_id,site_status,ID,Site_ID,Value,Local_Time
36,2023-07-27T01:00:00+10:00,7595301,1012,0b.EPA-1h.NOPK.EPA-24h,28.7,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1048,C,7595301,1012,28.7,NaT
40,2023-07-27T01:00:00+10:00,7595345,1014,0b.EPA-1h.NOPK.EPA-24h,30.3,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1045,C,7595345,1014,30.3,NaT
90,2023-07-27T02:00:00+10:00,7595459,1011,0b.EPA-1h.NOPK.EPA-24h,27.3,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1055,C,7595459,1011,27.3,NaT
95,2023-07-27T02:00:00+10:00,7595503,1012,0b.EPA-1h.NOPK.EPA-24h,28.9,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1048,C,7595503,1012,28.9,NaT
352,2023-07-27T07:00:00+10:00,7596538,1014,0b.EPA-1h.NOPK.EPA-24h,31.6,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1045,C,7596538,1014,31.6,NaT
539,2023-07-27T02:00:00+10:00,7595595,1016,0b.EPA-1h.NOPK.EPA-24h,33.6,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1049,C,7595595,1016,33.6,NaT
581,2023-07-27T03:00:00+10:00,7595659,1011,0b.EPA-1h.NOPK.EPA-24h,27.4,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1055,C,7595659,1011,27.4,NaT
586,2023-07-27T03:00:00+10:00,7595703,1012,0b.EPA-1h.NOPK.EPA-24h,28.9,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1048,C,7595703,1012,28.9,NaT
692,2023-07-27T05:00:00+10:00,7596013,1011,0b.EPA-1h.NOPK.EPA-24h,27.9,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1055,C,7596013,1011,27.9,NaT
702,2023-07-27T05:00:00+10:00,7596185,1016,0b.EPA-1h.NOPK.EPA-24h,33.6,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1049,C,7596185,1016,33.6,NaT
735,2023-07-27T06:00:00+10:00,7596250,1011,0b.EPA-1h.NOPK.EPA-24h,28.3,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1055,C,7596250,1011,28.3,NaT
740,2023-07-27T06:00:00+10:00,7596294,1012,0b.EPA-1h.NOPK.EPA-24h,29.5,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1048,C,7596294,1012,29.5,NaT
794,2023-07-27T07:00:00+10:00,7596586,1016,0b.EPA-1h.NOPK.EPA-24h,33.2,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1049,C,7596586,1016,33.2,NaT
835,2023-07-27T08:00:00+10:00,7596787,1016,0b.EPA-1h.NOPK.EPA-24h,32.6,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1049,C,7596787,1016,32.6,NaT
910,2023-07-27T01:00:00+10:00,7595257,1011,0b.EPA-1h.NOPK.EPA-24h,26.9,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1055,C,7595257,1011,26.9,NaT
918,2023-07-27T01:00:00+10:00,7595393,1016,0b.EPA-1h.NOPK.EPA-24h,33.7,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1049,C,7595393,1016,33.7,NaT
963,2023-07-27T02:00:00+10:00,7595547,1014,0b.EPA-1h.NOPK.EPA-24h,30.5,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1045,C,7595547,1014,30.5,NaT
1011,2023-07-27T03:00:00+10:00,7595747,1014,0b.EPA-1h.NOPK.EPA-24h,30.5,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1045,C,7595747,1014,30.5,NaT
1016,2023-07-27T03:00:00+10:00,7595795,1016,0b.EPA-1h.NOPK.EPA-24h,33.4,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1049,C,7595795,1016,33.4,NaT
1054,2023-07-27T04:00:00+10:00,7595861,1011,0b.EPA-1h.NOPK.EPA-24h,27.7,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1055,C,7595861,1011,27.7,NaT
1061,2023-07-27T04:00:00+10:00,7595905,1012,0b.EPA-1h.NOPK.EPA-24h,29.1,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1048,C,7595905,1012,29.1,NaT
1066,2023-07-27T04:00:00+10:00,7595949,1016,0b.EPA-1h.NOPK.EPA-24h,33.7,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1049,C,7595949,1016,33.7,NaT
1105,2023-07-27T05:00:00+10:00,7596057,1012,0b.EPA-1h.NOPK.EPA-24h,29.4,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1048,C,7596057,1012,29.4,NaT
1109,2023-07-27T05:00:00+10:00,7596109,1014,0b.EPA-1h.NOPK.EPA-24h,30.8,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1045,C,7596109,1014,30.8,NaT
1167,2023-07-27T06:00:00+10:00,7596338,1014,0b.EPA-1h.NOPK.EPA-24h,31.3,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1045,C,7596338,1014,31.3,NaT
1171,2023-07-27T06:00:00+10:00,7596386,1016,0b.EPA-1h.NOPK.EPA-24h,33.3,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1049,C,7596386,1016,33.3,NaT
1214,2023-07-27T07:00:00+10:00,7596450,1011,0b.EPA-1h.NOPK.EPA-24h,28.6,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1055,C,7596450,1011,28.6,NaT
1220,2023-07-27T07:00:00+10:00,7596494,1012,0b.EPA-1h.NOPK.EPA-24h,29.5,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1048,C,7596494,1012,29.5,NaT
1279,2023-07-27T08:00:00+10:00,7596651,1011,0b.EPA-1h.NOPK.EPA-24h,28.3,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1055,C,7596651,1011,28.3,NaT
1285,2023-07-27T08:00:00+10:00,7596695,1012,0b.EPA-1h.NOPK.EPA-24h,29.0,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1048,C,7596695,1012,29.0,NaT
1288,2023-07-27T08:00:00+10:00,7596739,1014,0b.EPA-1h.NOPK.EPA-24h,31.4,PM10-EPA-1h-NOPK-EPA-24h,ug/m^3,arc1045,C,7596739,1014,31.4,NaT