In [98]:
import pandas as pd
import numpy as np

In [106]:
# Load and display the data
df= pd.read_csv(r"C:\Users\USER\Capstone A\merged_data.csv")
df

,date,road_name,location,suburb,speed_limit,direction,time,vehicle_class_1,vehicle_class_2,vehicle_class_3,...,status_id,seg_descr,poly_area,gisid,street_id,seg_part,Geo Shape x,Geo Shape y,Latitude,Longitude
0,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,16:00,24.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
1,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,17:00,42.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
2,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,18:00,33.000000,0.386506,1.000000,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
3,2014-11-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,2:00,3.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
4,2014-11-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,4:00,86.177384,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63115,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,12:00,4.000000,0.386506,1.000000,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982
63116,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,13:00,6.000000,0.386506,4.093996,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982
63117,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,14:00,6.000000,0.386506,1.000000,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982
63118,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,16:00,8.000000,0.386506,1.000000,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982
63119,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,19:00,7.000000,0.386506,4.093996,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982

In [104]:
df.head()

,date,road_name,location,suburb,speed_limit,direction,time,vehicle_class_1,vehicle_class_2,vehicle_class_3,...,status_id,seg_descr,poly_area,gisid,street_id,seg_part,Geo Shape x,Geo Shape y,Latitude,Longitude
0,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,16:00,24.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
1,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,17:00,42.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
2,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,18:00,33.000000,0.386506,1.000000,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
3,2014-11-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,2:00,3.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
4,2014-11-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,4:00,86.177384,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383

In [96]:
df.tail()

,date,road_name,location,suburb,speed_limit,direction,time,Light_Vehicles,Light_Vehicles_with_Trailer,Two_Axle_Trucks_Buses,...,status_id,seg_descr,poly_area,gisid,street_id,seg_part,Geo Shape x,Geo Shape y,Latitude,Longitude
63115,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,12:00,4.0,0.386506,1.000000,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982
63116,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,13:00,6.0,0.386506,4.093996,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982
63117,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,14:00,6.0,0.386506,1.000000,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982
63118,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,16:00,8.0,0.386506,1.000000,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982
63119,2014-11-13,Tennyson Street,South West of Southey Street,Kensington,50,W,19:00,7.0,0.386506,4.093996,...,2,Tennyson Street between Southey Street and Ard...,1574,2289,1119,1,144.930478,-37.797832,-37.798036,144.929982

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63120 entries, 0 to 63119
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   63120 non-null  object
 1   road_name              63120 non-null  object
 2   location               63120 non-null  object
 3   suburb                 63120 non-null  object
 4   speed_limit            63120 non-null  int64
 5   direction              63120 non-null  object
 6   time                   63120 non-null  object
 7   vehicle_class_1        63120 non-null  float64
 8   vehicle_class_2        63120 non-null  float64
 9   vehicle_class_3        63120 non-null  float64
 10  vehicle_class_4        63120 non-null  float64
 11  vehicle_class_5        63120 non-null  float64
 12  vehicle_class_6        63120 non-null  float64
 13  vehicle_class_7        63120 non-null  float64
 14  vehicle_class_8        63120 non-null  float64
 15  vehicle_class_9        63120 non-null  float64
 16  vehicle_class_10       63120 non-null  float64
 17  vehicle_class_11       63120 non-null  float64
 18  vehicle_class_12       63120 non-null  float64
 19  vehicle_class_13       63120 non-null  float64
 20  motorcycle             63120 non-null  float64
 21  bike                   63120 non-null  float64
 22  average_speed          63120 non-null  float64
 23  85th_percentile_speed  63120 non-null  float64
 24  maximum_speed          63120 non-null  float64
 25  road_segment           63120 non-null  int64
 26  seg_id                 63120 non-null  int64
 27  str_type               63120 non-null  object
 28  dtupdate               63120 non-null  int64
 29  status_id              63120 non-null  int64
 30  seg_descr              63120 non-null  object
 31  poly_area              63120 non-null  int64
 32  gisid                  63120 non-null  int64
 33  street_id              63120 non-null  int64
 34  seg_part               63120 non-null  int64
 35  Geo Shape x            63120 non-null  float64
 36  Geo Shape y            63120 non-null  float64
 37  Latitude               63120 non-null  float64
 38  Longitude              63120 non-null  float64
dtypes: float64(22), int64(9), object(8)
memory usage: 18.8+ MB

In [70]:
# checking if the columns in the dataset have any nan values
df.isna().values.any()

False

In [74]:
#Checking date frequency
date_frequency = df['date'].value_counts()
print(date_frequency)

date
2015-04-09    960
2015-03-09    912
2015-05-09    720
2015-06-09    720
2014-11-11    672
             ...
2014-11-27     48
2016-02-25     24
2015-04-24     24
2015-04-25     24
2015-04-26     24
Name: count, Length: 404, dtype: int64

In [76]:
#Checking date range
min_date = df['date'].min()
max_date = df['date'].max()
print(f"{min_date} - {max_date}")

2014-01-06 - 2017-12-02

In [78]:
# Check for unique values in road_name and location fields
unique_road_names = df['road_name'].unique()
unique_locations = df['location'].unique()
unique_suburbs = df['suburb'].unique()

# Display the unique values
print("Unique Road Names:", len(unique_road_names), unique_road_names)
print("Unique Locations:",  len(unique_locations), unique_locations)
print("Unique Suburbs:", len(unique_suburbs), unique_suburbs)

Unique Road Names: 111 ['Wolseley Parade' 'Provost Street' 'Rankins Road' 'Rathdowne Street'
 'Rosslyn Street' 'Anderson Street' 'Spencer Street' 'Story Street'
 'Stubbs street' 'Wadey Street' 'Stubbs Street' 'Victoria Street'
 'Lothian Street' 'Abbotsford Street' 'Abbottsford Street'
 'Adderley Street' 'Agnes Street' 'Arden Street' 'Bateman Road'
 'Bayles Street' 'Berkeley Street' 'Bourke Street' 'Canning Street'
 'Cardigan Street' 'Clowe Street' 'Collett Street' 'Docklands Drive'
 'Drummond Street' 'Eastwood Street' 'Katherine Place' 'Flemington Road'
 'Gatehouse Street' 'Grattan Street' 'Highlander Lane' 'Lambeth Street'
 'Langford Street' 'Kirrip Crescent' 'Little Curzon Street'
 'Lt Lonsdale Street' 'Maxwell Lane' 'Miller Street'
 'Macarthur Place South' 'Morrah Street' 'Neil Street'
 "O'Shannassy Street" 'Park Drive' 'Queensberry Street' 'Carlton Street'
 'Charles Street' 'Degraves Street' 'Exhibition Street' 'Flinders Lane'
 'Flinders Street' 'Fogarty Street' 'Gatehouse Drive' 'Geographe Street'
 'Gracie Street' 'Haines Street' 'Haines St' 'Harbour Esplanade'
 'Hawke Street' 'Anthony Street' 'Barnett Street' 'Ireland Street'
 'Bellair Street' 'Boundary Road' 'Buncle Street' 'Marne Street'
 'Walsh Street' 'Park Street' 'Hope Street' 'The Ridgeway' 'Domain Street'
 'Domain St' 'Millswyn Street' 'Birdwood Avenue' 'Epsom Road'
 'Kensington Road' 'Little Bourke Street' 'Little Collins Street'
 'Little Lonsdale Street' 'Lloyd Street' 'Macaulay Road'
 'Little Palmerston Street' 'Lytton Street' 'Macarthur Place North'
 'McCrea Street' 'Melrose Street' 'Palmerston Street'
 'Princess Park Drive' 'The Avenue' 'Shiel Street' 'Wells Place'
 'Wells St' 'William Street' 'Bayswater Road' 'Elizabeth Street'
 'McConnell Street' 'Erskine Street' 'Gipps Street' 'Gordon Crescent'
 'Gower Street' 'Hampden Road' 'Henry Street' 'Kay Street' 'Smith Street'
 'Jolimont Street' 'Jolimont Terrace' 'King Street' 'Levers Street'
 'Tennyson Street']
Unique Locations: 146 ['North East of Derby Street' '30 Provost Street' 'North of Macaulay Road'
 'North of Eastwood Street'
 'Between Victoria Street and Queensberry Street midblock'
 'North of Pelham Street' 'Between King Street and William Street'
 '54 Anderson Street' 'North of Fairlie Court'
 'Between Abbottsford Street and Hawke Street'
 'Between Fitzgibbon Street and Jageurs Lane'
 'Between Gatehouse Street and Park Drive'
 'Between Smith Street and Parsons Street.' 'East of Wells Street'
 'West of St Kilda Road' 'Between Macaulay Road & Robertson Street'
 'Between Macaulay Road and Robertson Street'
 'Between Abbotsford Street and Curzon Street'
 'Between Howard Street & Peel Street'
 'Between Victoria Street and Queensberry Street' '126 Anderson Street'
 'Between Spencer Street and Ireland Street'
 'Between Ireland Street & Spencer Street'
 'Between Spencer Street and Miller Street' 'East of Hawke Street'
 'West of Hawke Street' 'Between Palmer Street and Wellington Parade'
 'East of Lloyd Street' 'Between Levesson Street and Chetwynd Street'
 'East of Fairbairn Drive' '26 Bateman Road'
 'Between Queensberry Street & Leicester Street'
 'Between Geographe Street and Import Lane'
 'Between Geographe Street & Navigation Drive' 'East of Vaughan Terrace'
 'West of Shands Lane' 'Between Elgin Street and Palmerston Street'
 'West of Punt Road' 'Between Waterloo Street and Lytton Street'
 'Between Smith Street and Parsons Street' 'South of Parsons Street'
 'Site1' 'Site2' 'South of Elgin Street' 'South of Flinders Lane'
 'North of Flinders Street' 'North of Macaulay Road & Robertson Street'
 'North of Robertson Street'
 'Between Grattan Street and Haymarket Roundabout'
 'Between Bayles Street and Park Drive'
 'Between Story Street and Morrah Street' 'East of Story Street'
 'Between Flemington Road and Royal Parade'
 'Between Flinders St and Flinders Lane'
 'Between Royal Parade and Berkeley Street' 'Midblock' 'North of Cade Way'
 'Between Elizabeth street and Queens Street' 'Just East of jolimont Lane'
 'Between Stawell Street & Anderson Street'
 'Between Rathdowne Street and Canning Street'
 'Between Abbottsford Street & Curzon Street'
 'Between Bayles Street and Degraves Street'
 'Between Flemington Road and Story Street'
 'Between Howard Street and Peel Street'
 'Between Canning Street and Nicholson Street'
 'Between Park Drive and Jageurs Lane'
 'Northbound - Between Flinders Street and Flinders Lane' 'Slip Lane'
 'Westbound - Between Spring Street and Wellington Parade South'
 'North East of Henderson Street' 'South of Stockmans Way'
 'Between Stockmans Way and The Crescent'
 'Between Smithfield Road and Stockmans Way'
 'Between Bayles Street and Morrah Street' 'South of Bourke Street'
 'East of Dryburgh Street' 'North East of Macaulay Rd'
 'North of Bourke Street' 'Spencer Street and King Street'
 'North of Adderley Street' 'Between Queensberry Street & Provost Street'
 'Mid Block' 'Between Miller and Victoria  Streets'
 'South of Adderley Street' 'Abbotsford Street to Hawke Street'
 'Between Macaulay Road & Wight Street' 'Just North of Gracie Street'
 'Between both Caylre Cresents at no Nth Bound Entry Point'
 'Betweenn Domain And Toorak Road' 'Between Domain and Toorak Road'
 '64 Park Street' 'At Entrance to Lost Dogs Home' '66 Hope Street'
 '9 The Ridgeway' '45 The Ridgeway' '63 Domain Street'
 'Between Toorak Road and Domain Road' '77 Millswyn Street'
 '71 Millswyn Street' 'West of Dallas Brooks Drive'
 'Between Bangalore Street and The Ridgeway' 'South West of Altona Street'
 'Between Exibition Street and Russell Street'
 'Between Russel Street and Swanston Street'
 'Between Spring Street and Exibition Street'
 'Between Russell Street and Swanston Street'
 'Between Rail Bridge & Gate U to Qube Logistics Driveway'
 'Between Bellair and Gower Streets'
 'Between Drummond Street and Rathdowne Street'
 'Between Lygon Street and Cardigan Street' 'East of Batman Hill Drive'
 'South East of Fogarty Street' 'South of Erskine Street'
 'Between Canning Street and Rathdowne Street'
 'South of MacPherson Street' 'East of Munster Terrace'
 'West of Munster Terrace' 'Between Capel Street and Howard Street'
 'Between Kay Street and Palmerston Street'
 'Between Adderley Street and Spencer Street'
 'Between Levers Street and Walker Street'
 'Between Dryborough and Canning Street'
 'Between Park Street and Levers Street'
 'Between Wells Street and Anthony Lane'
 'Bettween speed humps just South of Wadey Street'
 'Southbound - Between La Trobe Street and Little Lonsdale Street'
 'South West of Belmont Road'
 'Between Little Bourke Street and Bourke Street'
 'Between Lonsdale Street and Little Bourke Street'
 'South of Coote Street' 'Between Melrose Street and Dryburgh Street'
 'Between Clarendon Street and Powlett Street'
 'Between Powlett Street and Simpson Street'
 'Between Simpson Street and Hoddle Street' 'South East of Market Street'
 'North East of Durham Street'
 'Between Nicholson Street and Station Street'
 'Between Canning Street and Station Street' 'East of Barnett Street'
 'East of Collett Street' 'Dryburgh Street to Abbotsford Street'
 'Between Agnes Street and Charles Street'
 'Between Jolimont Street and Wellington Parade'
 'Between The Avenue and Royal Parade' 'South West of Southey Street']
Unique Suburbs: 12 ['Kensington' 'North Melbourne' 'Carlton' 'West Melbourne' 'South Yarra'
 'Parkville' 'Southbank' 'East Melbourne' 'Docklands' 'CARLTON'
 'Melbourne CBD' 'Carlton North']

In [82]:
# Replace "street" with "Street" (case-insensitive) 
df['road_name'] = df['road_name'].str.replace(r'\bstreet\b', 'Street', case=False, regex=True)

# Replace "St" with "Street"
df['road_name'] = df['road_name'].str.replace(r'\bSt\b', 'Street', regex=True)

# Replace "&" with "and"
df['location'] = df['location'].str.replace('&', 'and')
df['road_name'] = df['road_name'].str.replace('&', 'and')

# Display a sample of the cleaned data
df[['road_name', 'location']].drop_duplicates().head(20)

             road_name                                           location
0      Wolseley Parade                         North East of Derby Street
336     Provost Street                                  30 Provost Street
672       Rankins Road                             North of Macaulay Road
750       Rankins Road                           North of Eastwood Street
2016  Rathdowne Street  Between Victoria Street and Queensberry Street...
2352  Rathdowne Street                             North of Pelham Street
2688    Rosslyn Street             Between King Street and William Street
3024   Anderson Street                                 54 Anderson Street
3261   Anderson Street                             North of Fairlie Court
3696    Spencer Street        Between Abbottsford Street and Hawke Street
4032      Story Street         Between Fitzgibbon Street and Jageurs Lane
4704      Story Street            Between Gatehouse Street and Park Drive
5376     Stubbs Street           Between Smith Street and Parsons Street.
5712      Wadey Street                               East of Wells Street
5719      Wadey Street                              West of St Kilda Road
6384     Stubbs Street         Between Macaulay Road and Robertson Street
7056   Victoria Street        Between Abbotsford Street and Curzon Street
7392   Victoria Street              Between Howard Street and Peel Street
7728    Lothian Street     Between Victoria Street and Queensberry Street
8064   Anderson Street                                126 Anderson Street

In [84]:
unique_road_names = df['road_name'].unique()
unique_locations = df['location'].unique()
unique_suburbs = df['suburb'].unique()
print("Unique Road Names:", len(unique_road_names))
print("Unique Locations:",  len(unique_locations))
print("Unique Suburbs:", len(unique_suburbs))

Unique Road Names: 108
Unique Locations: 144
Unique Suburbs: 12

In [86]:
# Ensuring data consistency 
print('Data types of each column:\n', df.dtypes)

Data types of each column:
 date                      object
road_name                 object
location                  object
suburb                    object
speed_limit                int64
direction                 object
time                      object
vehicle_class_1          float64
vehicle_class_2          float64
vehicle_class_3          float64
vehicle_class_4          float64
vehicle_class_5          float64
vehicle_class_6          float64
vehicle_class_7          float64
vehicle_class_8          float64
vehicle_class_9          float64
vehicle_class_10         float64
vehicle_class_11         float64
vehicle_class_12         float64
vehicle_class_13         float64
motorcycle               float64
bike                     float64
average_speed            float64
85th_percentile_speed    float64
maximum_speed            float64
road_segment               int64
seg_id                     int64
str_type                  object
dtupdate                   int64
status_id                  int64
seg_descr                 object
poly_area                  int64
gisid                      int64
street_id                  int64
seg_part                   int64
Geo Shape x              float64
Geo Shape y              float64
Latitude                 float64
Longitude                float64
dtype: object

In [88]:
# Rename columns with descriptive names
column_mapping = {
    'vehicle_class_1': 'Light_Vehicles',
    'vehicle_class_2': 'Light_Vehicles_with_Trailer',
    'vehicle_class_3': 'Two_Axle_Trucks_Buses',
    'vehicle_class_4': 'Three_Axle_Trucks_Buses',
    'vehicle_class_5': 'Four_Axle_Trucks',
    'vehicle_class_6': 'Three_Axle_Articulated_Vehicles',
    'vehicle_class_7': 'Four_Axle_Articulated_Vehicles',
    'vehicle_class_8': 'Five_Axle_Articulated_Vehicles',
    'vehicle_class_9': 'Six_Axle_Articulated_Vehicles',
    'vehicle_class_10': 'B_Double_Trucks',
    'vehicle_class_11': 'Double_Road_Trains',
    'vehicle_class_12': 'Triple_Road_Trains',
    'vehicle_class_13': 'Unknown_Vehicles',
    'motorcycle': 'Motorcycles',
    'bike': 'Bicycles'
}
df.rename(columns=column_mapping, inplace=True)
df.head()

,date,road_name,location,suburb,speed_limit,direction,time,Light_Vehicles,Light_Vehicles_with_Trailer,Two_Axle_Trucks_Buses,...,status_id,seg_descr,poly_area,gisid,street_id,seg_part,Geo Shape x,Geo Shape y,Latitude,Longitude
0,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,16:00,24.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
1,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,17:00,42.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
2,2014-10-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,18:00,33.000000,0.386506,1.000000,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
3,2014-11-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,2:00,3.000000,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383
4,2014-11-11,Wolseley Parade,North East of Derby Street,Kensington,50,W,4:00,86.177384,0.386506,4.093996,...,2,Wolseley Parade between Bellair Street and Der...,5235,2301,1186,1,144.928291,-37.796994,-37.796238,144.929383

In [90]:
#Saving cleaned dataset
cleaned_data_path = r"C:\Users\USER\Capstone A\cleaned_merged_data.csv";
df.to_csv(cleaned_data_path, index=False)