# **Import modules & fetch data from Open Data Melbourne**

In [1]:
import requests
import pandas as pd
import os


# define function to fetch data from website using API

def fetch_data(base_url, dataset, api_key, num_records = 99, offset = 0):
    all_records = []
    max_offset = 9900  # Maximum number of requests

    while True:
        # maximum limit check
        if offset > max_offset:
            break

        # Create API request URL
        filters = f'{dataset}/records?limit={num_records}&offset={offset}'
        url = f'{base_url}{filters}&api_key={api_key}'

        # Start request
        try:
            result = requests.get(url, timeout=10)
            result.raise_for_status()
            records = result.json().get('results')
        except requests.exceptions.RequestException as e:
            raise Exception(f"API request failed: {e}")
        if records is None:
            break
        all_records.extend(records)
        if len(records) < num_records:
            break

        # next cycle offset
        offset += num_records

    # DataFrame all data
    df = pd.DataFrame(all_records)
    return df

API_KEY = os.environ.get('MELBOURNE_API_KEY', input("Please enter your API key: "))
BASE_URL = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/'

Please enter your API key: be95dc3bb26fd856f52d6bf1aaf777b2068541652c5da2dc57c3c431

# **Dataset:** Development activity monitor

## Load dataset

In [2]:
# get data
DEV_ACTIVITY = 'development-activity-monitor'

df_development = fetch_data(BASE_URL, DEV_ACTIVITY, API_KEY)

df_development.head()

,data_format,development_key,status,year_completed,clue_small_area,clue_block,street_address,property_id,property_id_2,property_id_3,...,hospital_flr,recreation_flr,publicdispaly_flr,community_flr,car_spaces,bike_spaces,town_planning_application,longitude,latitude,geopoint
0,Pre May 16,X000479,COMPLETED,2006,North Melbourne,342,191-201 Abbotsford Street NORTH MELBOURNE VIC ...,100023,None,None,...,0,0,0,0,0,0,0,144.945030,-37.802822,"{'lon': 144.9450298, 'lat': -37.80282184}"
1,Pre May 16,X000459,COMPLETED,2005,North Melbourne,333,218-224 Abbotsford Street NORTH MELBOURNE VIC ...,100119,None,None,...,0,0,0,0,0,0,0,144.945947,-37.802049,"{'lon': 144.9459475, 'lat': -37.80204879}"
2,Pre May 16,X000573,COMPLETED,2013,West Melbourne (Residential),414,56-62 Abbotsford Street WEST MELBOURNE VIC 3003,100144,None,None,...,0,0,0,0,0,0,0,144.944719,-37.806791,"{'lon': 144.9447186, 'lat': -37.80679128}"
3,Pre May 16,X000563,COMPLETED,2014,West Melbourne (Residential),409,1-9 Stawell Street WEST MELBOURNE VIC 3003,100441,None,None,...,0,0,0,0,0,28,0,144.942096,-37.806072,"{'lon': 144.9420962, 'lat': -37.80607242}"
4,Pre May 16,X000997,COMPLETED,2007,North Melbourne,1012,229-235 Arden Street NORTH MELBOURNE VIC 3051,100556,None,None,...,0,0,0,0,0,0,0,144.939286,-37.800374,"{'lon': 144.9392856, 'lat': -37.80037382}"

In [3]:
df_development.isna().sum()

data_format                       0
development_key                   0
status                            0
year_completed                  380
clue_small_area                   0
clue_block                        0
street_address                    0
property_id                       0
property_id_2                  1239
property_id_3                  1367
property_id_4                  1393
property_id_5                  1403
floors_above                      0
resi_dwellings                    0
studio_dwe                        0
one_bdrm_dwe                      0
two_bdrm_dwe                      0
three_bdrm_dwe                    0
student_apartments                0
student_beds                      0
student_accommodation_units       0
institutional_accom_beds          0
hotel_rooms                       0
serviced_apartments               0
hotels_serviced_apartments        0
hostel_beds                       0
childcare_places                  0
office_flr                        0
retail_flr                        0
industrial_flr                    0
storage_flr                       0
education_flr                     0
hospital_flr                      0
recreation_flr                    0
publicdispaly_flr                 0
community_flr                     0
car_spaces                        0
bike_spaces                       0
town_planning_application         0
longitude                         0
latitude                          0
geopoint                          0
dtype: int64

## Data cleaning

### Fill 'property_id_5' and remove unwanted columns

In [4]:
# save as a new dataset to preserve the original data

df_dev_filled = df_development.copy()

# fill 'property_id_5' with values from 'property_id_4', then 'property_id_3', then 'property_id_2', then 'property_id'

df_dev_filled['property_id_5'] = df_dev_filled['property_id_5'].fillna(df_dev_filled['property_id_4']).fillna(df_dev_filled['property_id_3']).fillna(df_dev_filled['property_id_2']).fillna(df_dev_filled['property_id'])

# drop 'property_id_4' to 'property_id', and other unwanted columns

df_dev_filled.drop(['property_id_4', 'property_id_3', 'property_id_2', 'property_id', 'data_format', 'development_key', 'town_planning_application'], axis = 1, inplace = True)

len(df_dev_filled)

1406

In [5]:
df_dev_filled.head()

,status,year_completed,clue_small_area,clue_block,street_address,property_id_5,floors_above,resi_dwellings,studio_dwe,one_bdrm_dwe,...,education_flr,hospital_flr,recreation_flr,publicdispaly_flr,community_flr,car_spaces,bike_spaces,longitude,latitude,geopoint
0,COMPLETED,2006,North Melbourne,342,191-201 Abbotsford Street NORTH MELBOURNE VIC ...,100023,2,17,0,0,...,0,0,0,0,0,0,0,144.945030,-37.802822,"{'lon': 144.9450298, 'lat': -37.80282184}"
1,COMPLETED,2005,North Melbourne,333,218-224 Abbotsford Street NORTH MELBOURNE VIC ...,100119,3,12,0,0,...,0,0,0,0,0,0,0,144.945947,-37.802049,"{'lon': 144.9459475, 'lat': -37.80204879}"
2,COMPLETED,2013,West Melbourne (Residential),414,56-62 Abbotsford Street WEST MELBOURNE VIC 3003,100144,4,3,0,0,...,0,0,0,0,0,0,0,144.944719,-37.806791,"{'lon': 144.9447186, 'lat': -37.80679128}"
3,COMPLETED,2014,West Melbourne (Residential),409,1-9 Stawell Street WEST MELBOURNE VIC 3003,100441,3,28,0,17,...,0,0,0,0,0,0,28,144.942096,-37.806072,"{'lon': 144.9420962, 'lat': -37.80607242}"
4,COMPLETED,2007,North Melbourne,1012,229-235 Arden Street NORTH MELBOURNE VIC 3051,100556,2,0,0,0,...,0,0,0,0,0,0,0,144.939286,-37.800374,"{'lon': 144.9392856, 'lat': -37.80037382}"

In [6]:
df_dev_filled.isna().sum()

status                           0
year_completed                 380
clue_small_area                  0
clue_block                       0
street_address                   0
property_id_5                    0
floors_above                     0
resi_dwellings                   0
studio_dwe                       0
one_bdrm_dwe                     0
two_bdrm_dwe                     0
three_bdrm_dwe                   0
student_apartments               0
student_beds                     0
student_accommodation_units      0
institutional_accom_beds         0
hotel_rooms                      0
serviced_apartments              0
hotels_serviced_apartments       0
hostel_beds                      0
childcare_places                 0
office_flr                       0
retail_flr                       0
industrial_flr                   0
storage_flr                      0
education_flr                    0
hospital_flr                     0
recreation_flr                   0
publicdispaly_flr                0
community_flr                    0
car_spaces                       0
bike_spaces                      0
longitude                        0
latitude                         0
geopoint                         0
dtype: int64

In [7]:
# rename 'property_id_5'
df_dev_filled.rename(columns = {'property_id_5': 'property_id'}, inplace = True)

# check the dataframe
df_dev_filled.head()

,status,year_completed,clue_small_area,clue_block,street_address,property_id,floors_above,resi_dwellings,studio_dwe,one_bdrm_dwe,...,education_flr,hospital_flr,recreation_flr,publicdispaly_flr,community_flr,car_spaces,bike_spaces,longitude,latitude,geopoint
0,COMPLETED,2006,North Melbourne,342,191-201 Abbotsford Street NORTH MELBOURNE VIC ...,100023,2,17,0,0,...,0,0,0,0,0,0,0,144.945030,-37.802822,"{'lon': 144.9450298, 'lat': -37.80282184}"
1,COMPLETED,2005,North Melbourne,333,218-224 Abbotsford Street NORTH MELBOURNE VIC ...,100119,3,12,0,0,...,0,0,0,0,0,0,0,144.945947,-37.802049,"{'lon': 144.9459475, 'lat': -37.80204879}"
2,COMPLETED,2013,West Melbourne (Residential),414,56-62 Abbotsford Street WEST MELBOURNE VIC 3003,100144,4,3,0,0,...,0,0,0,0,0,0,0,144.944719,-37.806791,"{'lon': 144.9447186, 'lat': -37.80679128}"
3,COMPLETED,2014,West Melbourne (Residential),409,1-9 Stawell Street WEST MELBOURNE VIC 3003,100441,3,28,0,17,...,0,0,0,0,0,0,28,144.942096,-37.806072,"{'lon': 144.9420962, 'lat': -37.80607242}"
4,COMPLETED,2007,North Melbourne,1012,229-235 Arden Street NORTH MELBOURNE VIC 3051,100556,2,0,0,0,...,0,0,0,0,0,0,0,144.939286,-37.800374,"{'lon': 144.9392856, 'lat': -37.80037382}"

### Fix duplicated value in 'property_id_5' if any

In [8]:
# identify duplicates in 'property_id' if any
dup = df_dev_filled[df_dev_filled.duplicated(subset = 'property_id', keep = False)]

# sort these duplicates by 'property_id' and then by 'year_completed' in descending order
dup_sorted = dup.sort_values(by = ['property_id', 'year_completed'], ascending = [True, False])

# display rows where 'property_id' has duplicates
print(dup_sorted)

len(dup_sorted)

                  status year_completed               clue_small_area  \
460   UNDER CONSTRUCTION           None  West Melbourne (Residential)
1383  UNDER CONSTRUCTION           None  West Melbourne (Residential)
307            COMPLETED           2019  West Melbourne (Residential)
776            COMPLETED           2019  West Melbourne (Residential)
435             APPROVED           None  West Melbourne (Residential)
...                  ...            ...                           ...
1177           COMPLETED           2017  West Melbourne (Residential)
343            COMPLETED           2023               Melbourne (CBD)
1281           COMPLETED           2023               Melbourne (CBD)
1274           COMPLETED           2023               Melbourne (CBD)
1275           COMPLETED           2023               Melbourne (CBD)

      clue_block                                   street_address property_id  \
460          412  17-37 Abbotsford Street WEST MELBOURNE VIC 3003      100002
1383         412  17-37 Abbotsford Street WEST MELBOURNE VIC 3003      100002
307          444     83-113 Batman Street WEST MELBOURNE VIC 3003      100852
776          444     83-113 Batman Street WEST MELBOURNE VIC 3003      100852
435          111           68 Batman Street, West Melbourne, 3003      100856
...          ...                                              ...         ...
1177         440    130-154 Dudley Street WEST MELBOURNE VIC 3003      679273
343           88     310-326 Exhibition Street MELBOURNE VIC 3000      692091
1281          88     310-326 Exhibition Street MELBOURNE VIC 3000      692091
1274          71        244-276 Spencer Street MELBOURNE VIC 3000      694372
1275          71        244-276 Spencer Street MELBOURNE VIC 3000      694372

      floors_above  resi_dwellings  studio_dwe  one_bdrm_dwe  ...  \
460             12             163           0            24  ...
1383             4              16           0             0  ...
307             21             169           0            91  ...
776             26             360           0           208  ...
435              5               0           0             0  ...
...            ...             ...         ...           ...  ...
1177             9              80           5            39  ...
343             58             325           0            76  ...
1281            59               0           0             0  ...
1274            68             575           0           289  ...
1275            72             849           0           466  ...

      education_flr  hospital_flr  recreation_flr  publicdispaly_flr  \
460               0             0               0                  0
1383              0             0               0                  0
307               0             0               0                  0
776               0             0               0                  0
435               0             0               0                  0
...             ...           ...             ...                ...
1177              0             0               0                  0
343               0             0               0                  0
1281              0             0               0                  0
1274              0             0               0                  0
1275              0             0               0                  0

      community_flr  car_spaces  bike_spaces   longitude   latitude  \
460               0         234           60  144.943418 -37.807178
1383              0           0            0  144.943418 -37.807178
307               0           0            0  144.949913 -37.811595
776               0         515          444  144.949913 -37.811595
435               0          13           23  144.950848 -37.810601
...             ...         ...          ...         ...        ...
1177              0           0            0  144.950614 -37.809522
343               0         290          266  144.969566 -37.808274
1281              0           0            0  144.969566 -37.808274
1274              0         320            0  144.953371 -37.814257
1275              0         480            0  144.953371 -37.814257

                                       geopoint
460   {'lon': 144.9434178, 'lat': -37.80717803}
1383  {'lon': 144.9434178, 'lat': -37.80717803}
307   {'lon': 144.9499131, 'lat': -37.81159519}
776   {'lon': 144.9499131, 'lat': -37.81159519}
435   {'lon': 144.9508476, 'lat': -37.81060129}
...                                         ...
1177  {'lon': 144.9506136, 'lat': -37.80952166}
343   {'lon': 144.9695659, 'lat': -37.80827441}
1281  {'lon': 144.9695659, 'lat': -37.80827441}
1274  {'lon': 144.9533708, 'lat': -37.81425664}
1275  {'lon': 144.9533708, 'lat': -37.81425664}

[373 rows x 35 columns]

373

In [9]:
# drop duplicates and those are under construnction
# keeping the first (which has the latest year) if years are different

df_dev_clean = df_dev_filled.drop(dup_sorted[dup_sorted.duplicated(subset = 'property_id', keep = 'first')].index)

print(df_dev_clean)

                  status year_completed               clue_small_area  \
0              COMPLETED           2006               North Melbourne
1              COMPLETED           2005               North Melbourne
2              COMPLETED           2013  West Melbourne (Residential)
3              COMPLETED           2014  West Melbourne (Residential)
4              COMPLETED           2007               North Melbourne
...                  ...            ...                           ...
1401  UNDER CONSTRUCTION           None                       Carlton
1402  UNDER CONSTRUCTION           None                East Melbourne
1403  UNDER CONSTRUCTION           None                     Southbank
1404  UNDER CONSTRUCTION           None                East Melbourne
1405  UNDER CONSTRUCTION           None               North Melbourne

      clue_block                                     street_address  \
0            342  191-201 Abbotsford Street NORTH MELBOURNE VIC ...
1            333  218-224 Abbotsford Street NORTH MELBOURNE VIC ...
2            414    56-62 Abbotsford Street WEST MELBOURNE VIC 3003
3            409         1-9 Stawell Street WEST MELBOURNE VIC 3003
4           1012      229-235 Arden Street NORTH MELBOURNE VIC 3051
...          ...                                                ...
1401         245               86-94 Pelham Street CARLTON VIC 3053
1402         620        250-260 Albert Street, East Melbourne, 3002
1403         807      84-90 Queens Bridge Street SOUTHBANK VIC 3006
1404         621      364-370 Albert Street EAST MELBOURNE VIC 3002
1405        2383       139-149 Boundary Road, North Melbourne, 3051

     property_id  floors_above  resi_dwellings  studio_dwe  one_bdrm_dwe  ...  \
0         100023             2              17           0             0  ...
1         100119             3              12           0             0  ...
2         100144             4               3           0             0  ...
3         100441             3              28           0            17  ...
4         100556             2               0           0             0  ...
...          ...           ...             ...         ...           ...  ...
1401      107554             7              36           0             0  ...
1402      100361             9              23           0             0  ...
1403      110440            66             372           0           140  ...
1404      100355             9              14           0             0  ...
1405      616902            12             276           0           102  ...

      education_flr  hospital_flr  recreation_flr  publicdispaly_flr  \
0                 0             0               0                  0
1                 0             0               0                  0
2                 0             0               0                  0
3                 0             0               0                  0
4                 0             0               0                  0
...             ...           ...             ...                ...
1401              0             0               0                  0
1402              0             0               0                  0
1403              0             0               0                  0
1404              0             0               0                  0
1405              0             0               0                  0

      community_flr  car_spaces  bike_spaces   longitude   latitude  \
0                 0           0            0  144.945030 -37.802822
1                 0           0            0  144.945947 -37.802049
2                 0           0            0  144.944719 -37.806791
3                 0           0           28  144.942096 -37.806072
4                 0           0            0  144.939286 -37.800374
...             ...         ...          ...         ...        ...
1401              0          56          137  144.964800 -37.802300
1402              0          35           25  144.982577 -37.809940
1403              0         111          153  144.959900 -37.825000
1404              0          58           39  144.978950 -37.809569
1405              0         234          225  144.939255 -37.790192

                                       geopoint
0     {'lon': 144.9450298, 'lat': -37.80282184}
1     {'lon': 144.9459475, 'lat': -37.80204879}
2     {'lon': 144.9447186, 'lat': -37.80679128}
3     {'lon': 144.9420962, 'lat': -37.80607242}
4     {'lon': 144.9392856, 'lat': -37.80037382}
...                                         ...
1401         {'lon': 144.9648, 'lat': -37.8023}
1402  {'lon': 144.9825767, 'lat': -37.80993999}
1403          {'lon': 144.9599, 'lat': -37.825}
1404  {'lon': 144.9789497, 'lat': -37.80956912}
1405  {'lon': 144.9392553, 'lat': -37.79019229}

[1174 rows x 35 columns]

In [10]:
## check if there still have duplicated values in 'property_id'

dup_2 = df_dev_clean[df_dev_clean.duplicated(subset = 'property_id', keep = False)]

In [11]:
print(dup_2)

len(dup_2)

Empty DataFrame
Columns: [status, year_completed, clue_small_area, clue_block, street_address, property_id, floors_above, resi_dwellings, studio_dwe, one_bdrm_dwe, two_bdrm_dwe, three_bdrm_dwe, student_apartments, student_beds, student_accommodation_units, institutional_accom_beds, hotel_rooms, serviced_apartments, hotels_serviced_apartments, hostel_beds, childcare_places, office_flr, retail_flr, industrial_flr, storage_flr, education_flr, hospital_flr, recreation_flr, publicdispaly_flr, community_flr, car_spaces, bike_spaces, longitude, latitude, geopoint]
Index: []

[0 rows x 35 columns]

0

In [12]:
# remove 'office_flr', 'retail_flr', 'industrial_flr', 'storage_flr', 'education_flr', 'hospital_flr', 'recreation_flr', 'publicdispaly_flr', 'community_flr'


---

In [13]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [14]:
df_dev_filled.to_csv('/content/gdrive/My Drive/Colab Notebooks/df_dev_filled.csv', index = False)

# **Dataset:** Residential dwellings

## Load dataset

In [15]:
# get data
RES_DWELLINGS = 'residential-dwellings'

df_residential = fetch_data(BASE_URL, RES_DWELLINGS, API_KEY)

df_residential.head()

,census_year,block_id,property_id,base_property_id,building_address,clue_small_area,dwelling_type,dwelling_number,longitude,latitude,location
0,2017,355,107908,107908,463 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.952007,-37.803558,"{'lon': 144.95200710155, 'lat': -37.8035582919..."
1,2017,355,107910,107910,467 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.951877,-37.803541,"{'lon': 144.95187690720002, 'lat': -37.8035406..."
2,2017,355,107913,107913,477 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.951609,-37.803527,"{'lon': 144.95160858014998, 'lat': -37.8035273..."
3,2017,355,107914,107914,479 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.951550,-37.803521,"{'lon': 144.95154960515, 'lat': -37.8035207254..."
4,2017,355,107915,107915,481 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.951488,-37.803514,"{'lon': 144.95148784765, 'lat': -37.8035138005..."

In [16]:
df_residential.isna().sum()   # check if there are nulls

census_year          0
block_id             0
property_id          0
base_property_id     0
building_address     0
clue_small_area      0
dwelling_type        0
dwelling_number      0
longitude           43
latitude            43
location            43
dtype: int64

In [17]:
len(df_residential)

9999

## Data cleaning

In [18]:
# drop 'base_property_id'
df_res_dropped = df_residential.drop(['base_property_id'], axis = 1)

df_res_dropped.head()

,census_year,block_id,property_id,building_address,clue_small_area,dwelling_type,dwelling_number,longitude,latitude,location
0,2017,355,107908,463 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.952007,-37.803558,"{'lon': 144.95200710155, 'lat': -37.8035582919..."
1,2017,355,107910,467 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.951877,-37.803541,"{'lon': 144.95187690720002, 'lat': -37.8035406..."
2,2017,355,107913,477 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.951609,-37.803527,"{'lon': 144.95160858014998, 'lat': -37.8035273..."
3,2017,355,107914,479 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.951550,-37.803521,"{'lon': 144.95154960515, 'lat': -37.8035207254..."
4,2017,355,107915,481 Queensberry Street NORTH MELBOURNE 3051,North Melbourne,House/Townhouse,1,144.951488,-37.803514,"{'lon': 144.95148784765, 'lat': -37.8035138005..."

In [19]:
# duplicate ID checking on 'property_id'
# if any, keep row with the latest year

# sort dataframe by 'property_id' then 'census_year' (latest year first for each group of 'property_id')
df_res_sorted = df_res_dropped.sort_values(by = ['property_id', 'census_year'], ascending = [True, False])

# drop duplicates in 'property_id', keeping only the row with the latest year in 'census_year'
df_res_cleaned = df_res_sorted.drop_duplicates(subset = 'property_id', keep = 'first')

print(df_res_cleaned)

     census_year  block_id property_id  \
5995        2006       528           1
3574        2019       411      100001
5245        2006       342      100011
4660        2019       342      100014
4661        2019       342      100015
...          ...       ...         ...
3221        2019       346      681458
1766        2018      2531      681562
3949        2019       527      681850
3170        2019      1108      688500
4671        2019       342      690277

                                    building_address  \
5995          23-25 Wakefield Street KENSINGTON 3031
3574      1-13 Abbotsford Street WEST MELBOURNE 3003
5245  151-153 Abbotsford Street NORTH MELBOURNE 3051
4660  163-165 Abbotsford Street NORTH MELBOURNE 3051
4661      167 Abbotsford Street NORTH MELBOURNE 3051
...                                              ...
3221          17 Purcell Street NORTH MELBOURNE 3051
1766            17 Nottingham Street KENSINGTON 3031
3949            52 Newton Street KENSINGTON VIC 3031
3170             883-0 Collins Street DOCKLANDS 3008
4671      161 Abbotsford Street NORTH MELBOURNE 3051

                   clue_small_area           dwelling_type  dwelling_number  \
5995                    Kensington         House/Townhouse                1
3574  West Melbourne (Residential)         House/Townhouse               10
5245               North Melbourne         House/Townhouse                1
4660               North Melbourne         House/Townhouse                1
4661               North Melbourne         House/Townhouse                1
...                            ...                     ...              ...
3221               North Melbourne         House/Townhouse                1
1766                    Kensington         House/Townhouse                1
3949                    Kensington         House/Townhouse                1
3170                     Docklands  Residential Apartments              222
4671               North Melbourne         House/Townhouse                1

       longitude   latitude                                           location
5995  144.920860 -37.797337  {'lon': 144.92085972771906, 'lat': -37.7973370...
3574  144.943283 -37.807923  {'lon': 144.9432825115, 'lat': -37.80792336045...
5245  144.945002 -37.803831  {'lon': 144.94500235860917, 'lat': -37.8038311...
4660  144.945041 -37.803560  {'lon': 144.9450413446424, 'lat': -37.80356036...
4661  144.945053 -37.803493  {'lon': 144.94505345384158, 'lat': -37.8034931...
...          ...        ...                                                ...
3221  144.948791 -37.802292  {'lon': 144.9487905821, 'lat': -37.80229223600...
1766  144.932897 -37.789663  {'lon': 144.9328965152812, 'lat': -37.7896631912}
3949  144.922906 -37.796131  {'lon': 144.92290623865, 'lat': -37.7961307772...
3170  144.942980 -37.821497  {'lon': 144.94297959762804, 'lat': -37.8214969...
4671  144.945102 -37.803635  {'lon': 144.94510193151137, 'lat': -37.8036345...

[6734 rows x 10 columns]

In [20]:
df_res_cleaned.isna().sum()

census_year          0
block_id             0
property_id          0
building_address     0
clue_small_area      0
dwelling_type        0
dwelling_number      0
longitude           24
latitude            24
location            24
dtype: int64

# **Dataset:** Building information

## Load dataset

In [21]:
# get data
BUILDING_INFO = 'buildings-with-name-age-size-accessibility-and-bicycle-facilities'

df_bldg_info = fetch_data(BASE_URL, BUILDING_INFO, API_KEY)

df_bldg_info.head()

,census_year,block_id,property_id,base_property_id,building_name,street_address,clue_small_area,construction_year,refurbished_year,number_of_floors_above_ground,predominant_space_use,accessibility_type,accessibility_type_description,accessibility_rating,bicycle_spaces,has_showers,longitude,latitude,location
0,2003,608,104285,104285,None,84 George Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987521,-37.815299,"{'lon': 144.9875211528448, 'lat': -37.81529934..."
1,2003,608,104287,104287,None,80 George Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987677,-37.815316,"{'lon': 144.98767742034823, 'lat': -37.8153163..."
2,2003,608,104947,104947,None,81-83 Hotham Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987589,-37.814577,"{'lon': 144.98758896457355, 'lat': -37.8145774..."
3,2003,608,104948,104948,None,87 Hotham Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987486,-37.814572,"{'lon': 144.9874861960862, 'lat': -37.81457155..."
4,2003,608,104949,104949,None,89 Hotham Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,Residential Apartment,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987408,-37.814593,"{'lon': 144.98740820504202, 'lat': -37.8145933..."

In [22]:
df_bldg_info.isna().sum()   # check if there are nulls

census_year                          0
block_id                             0
property_id                          0
base_property_id                     0
building_name                     7808
street_address                       0
clue_small_area                      0
construction_year                 4399
refurbished_year                  8392
number_of_floors_above_ground        6
predominant_space_use                0
accessibility_type                1020
accessibility_type_description    1020
accessibility_rating              1020
bicycle_spaces                    6035
has_showers                       9999
longitude                          434
latitude                           434
location                           434
dtype: int64

In [23]:
len(df_bldg_info)

9999

## Data cleaning

In [24]:
# drop 'base_property_id' for 'df_bldg_info' dataset
df_bldg_dropped = df_bldg_info.drop(['base_property_id', 'building_name'], axis = 1)

df_bldg_dropped.head()

,census_year,block_id,property_id,street_address,clue_small_area,construction_year,refurbished_year,number_of_floors_above_ground,predominant_space_use,accessibility_type,accessibility_type_description,accessibility_rating,bicycle_spaces,has_showers,longitude,latitude,location
0,2003,608,104285,84 George Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987521,-37.815299,"{'lon': 144.9875211528448, 'lat': -37.81529934..."
1,2003,608,104287,80 George Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987677,-37.815316,"{'lon': 144.98767742034823, 'lat': -37.8153163..."
2,2003,608,104947,81-83 Hotham Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987589,-37.814577,"{'lon': 144.98758896457355, 'lat': -37.8145774..."
3,2003,608,104948,87 Hotham Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987486,-37.814572,"{'lon': 144.9874861960862, 'lat': -37.81457155..."
4,2003,608,104949,89 Hotham Street EAST MELBOURNE 3002,East Melbourne,None,None,2.0,Residential Apartment,Not determined or not applicable,Building is not considered to be publicly acce...,0,NaN,None,144.987408,-37.814593,"{'lon': 144.98740820504202, 'lat': -37.8145933..."

In [25]:
# duplicate ID checking on 'property_id'
# if any, keep row with the latest year

# sort dataframe by 'property_id' then 'census_year' (latest year first for each group of 'property_id')
df_bldg_sorted = df_bldg_dropped.sort_values(by = ['property_id', 'census_year'], ascending = [True, False])

# drop duplicates in 'property_id', keeping only the row with the latest year in 'census_year'
df_bldg_cleaned = df_bldg_sorted.drop_duplicates(subset = 'property_id', keep = 'first')

print(df_bldg_cleaned)

     census_year  block_id property_id  \
6362        2017       411      100001
2863        2004       412      100002
6363        2017       413      100003
6364        2017       413      100004
5838        2017       342      100009
...          ...       ...         ...
7140        2021       736      706730
4173        2021        87      707517
9132        2020        37      709874
6802        2021       568      712803
4193        2021        94      713467

                                        street_address  \
6362        1-13 Abbotsford Street WEST MELBOURNE 3003
2863       17-37 Abbotsford Street WEST MELBOURNE 3003
6363       39-49 Abbotsford Street WEST MELBOURNE 3003
6364       51-57 Abbotsford Street WEST MELBOURNE 3003
5838    135-141 Abbotsford Street NORTH MELBOURNE 3051
...                                                ...
7140           37-47 Balston Street SOUTHBANK VIC 3006
4173      303-307 Exhibition Street MELBOURNE VIC 3000
9132  101-107 Little Collins Street MELBOURNE VIC 3000
6802             6 Gilbertson Walk KENSINGTON VIC 3031
4193       143-171 A'Beckett Street MELBOURNE VIC 3000

                   clue_small_area construction_year refurbished_year  \
6362  West Melbourne (Residential)              2012             None
2863  West Melbourne (Residential)              1920             None
6363  West Melbourne (Residential)              1985             2000
6364  West Melbourne (Residential)              2000             None
5838               North Melbourne              1980             None
...                            ...               ...              ...
7140                     Southbank              2018             None
4173               Melbourne (CBD)              None             None
9132               Melbourne (CBD)              None             None
6802                    Kensington              2020             None
4193               Melbourne (CBD)              2021             None

      number_of_floors_above_ground              predominant_space_use  \
6362                            4.0                    House/Townhouse
2863                            2.0                          Wholesale
6363                            1.0                    Workshop/Studio
6364                            3.0              Residential Apartment
5838                            2.0                             Office
...                             ...                                ...
7140                            1.0                Unoccupied - Unused
4173                            2.0  Entertainment/Recreation - Indoor
9132                           26.0    Unoccupied - Under Construction
6802                            2.0                    House/Townhouse
4193                           81.0    Unoccupied - Under Construction

                    accessibility_type  \
6362        Low level of accessibility
2863        Low level of accessibility
6363        Low level of accessibility
6364        Low level of accessibility
5838        Low level of accessibility
...                                ...
7140        Low level of accessibility
4173        Low level of accessibility
9132       High level of accessibility
6802  Not determined or not applicable
4193  Not determined or not applicable

                         accessibility_type_description accessibility_rating  \
6362                           All entrances have steps                    1
2863                           All entrances have steps                    1
6363                           All entrances have steps                    1
6364                           All entrances have steps                    1
5838                           All entrances have steps                    1
...                                                 ...                  ...
7140                           All entrances have steps                    1
4173                           All entrances have steps                    1
9132  Main Entrance is at grade and has no steps or ...                    3
6802  Building is not considered to be publicly acce...                    0
4193  Building is not considered to be publicly acce...                    0

      bicycle_spaces has_showers   longitude   latitude  \
6362             0.0        None  144.943283 -37.807923
2863             NaN        None  144.943430 -37.807178
6363             0.0        None  144.944043 -37.806836
6364             0.0        None  144.944180 -37.806637
5838             0.0        None  144.944965 -37.804143
...              ...         ...         ...        ...
7140             0.0        None  144.963066 -37.826287
4173             0.0        None  144.968773 -37.808814
9132             0.0        None  144.970686 -37.813639
6802             0.0        None  144.922356 -37.790790
4193             0.0        None  144.959096 -37.810022

                                               location
6362  {'lon': 144.9432825115, 'lat': -37.80792336045...
2863  {'lon': 144.943430449207, 'lat': -37.807177559...
6363  {'lon': 144.94404316635, 'lat': -37.8068363916...
6364  {'lon': 144.94418011208475, 'lat': -37.8066369...
5838  {'lon': 144.94496541119372, 'lat': -37.8041427...
...                                                 ...
7140  {'lon': 144.96306641553016, 'lat': -37.8262868...
4173  {'lon': 144.96877272385723, 'lat': -37.8088140...
9132  {'lon': 144.9706863215771, 'lat': -37.81363930...
6802  {'lon': 144.9223556426, 'lat': -37.7907903667807}
4193  {'lon': 144.95909557947851, 'lat': -37.8100224...

[7472 rows x 17 columns]

# **Merging**

### Merge 'Development activity monitor' and 'Residential dwellings'

In [26]:
list(df_dev_clean)

['status',
 'year_completed',
 'clue_small_area',
 'clue_block',
 'street_address',
 'property_id',
 'floors_above',
 'resi_dwellings',
 'studio_dwe',
 'one_bdrm_dwe',
 'two_bdrm_dwe',
 'three_bdrm_dwe',
 'student_apartments',
 'student_beds',
 'student_accommodation_units',
 'institutional_accom_beds',
 'hotel_rooms',
 'serviced_apartments',
 'hotels_serviced_apartments',
 'hostel_beds',
 'childcare_places',
 'office_flr',
 'retail_flr',
 'industrial_flr',
 'storage_flr',
 'education_flr',
 'hospital_flr',
 'recreation_flr',
 'publicdispaly_flr',
 'community_flr',
 'car_spaces',
 'bike_spaces',
 'longitude',
 'latitude',
 'geopoint']

In [27]:
list(df_res_cleaned)

['census_year',
 'block_id',
 'property_id',
 'building_address',
 'clue_small_area',
 'dwelling_type',
 'dwelling_number',
 'longitude',
 'latitude',
 'location']

In [28]:
# skip duplicated columns while merging:
# 'block_id', 'clue_small_area', 'street_address', 'longitude', 'latitude' and 'geopoint'

dev_exclude = ['street_address', 'longitude', 'latitude', 'geopoint']
df_dev_selected = df_dev_clean.drop(dev_exclude, axis = 1)

df_res_selected = df_res_cleaned[['census_year', 'property_id', 'building_address', 'dwelling_type', 'dwelling_number', 'longitude', 'latitude', 'location']]

In [29]:
# inner join

inner_dev_res = pd.merge(df_dev_selected, df_res_selected, on = 'property_id', how = 'inner')

len(inner_dev_res)

250

In [30]:
# outer join

outer_dev_res = pd.merge(df_dev_selected, df_res_selected, on = 'property_id', how = 'outer')

len(outer_dev_res)

7658

In [31]:
# right join

right_dev_res = pd.merge(df_dev_selected, df_res_selected, on = 'property_id', how = 'right')

len(right_dev_res)

6734

In [32]:
# left join

left_dev_res = pd.merge(df_dev_selected, df_res_selected, on = 'property_id', how = 'left')

len(left_dev_res)

1174

In [33]:
list(left_dev_res.columns)

['status',
 'year_completed',
 'clue_small_area',
 'clue_block',
 'property_id',
 'floors_above',
 'resi_dwellings',
 'studio_dwe',
 'one_bdrm_dwe',
 'two_bdrm_dwe',
 'three_bdrm_dwe',
 'student_apartments',
 'student_beds',
 'student_accommodation_units',
 'institutional_accom_beds',
 'hotel_rooms',
 'serviced_apartments',
 'hotels_serviced_apartments',
 'hostel_beds',
 'childcare_places',
 'office_flr',
 'retail_flr',
 'industrial_flr',
 'storage_flr',
 'education_flr',
 'hospital_flr',
 'recreation_flr',
 'publicdispaly_flr',
 'community_flr',
 'car_spaces',
 'bike_spaces',
 'census_year',
 'building_address',
 'dwelling_type',
 'dwelling_number',
 'longitude',
 'latitude',
 'location']

In [34]:
print(left_dev_res)

                  status year_completed               clue_small_area  \
0              COMPLETED           2006               North Melbourne
1              COMPLETED           2005               North Melbourne
2              COMPLETED           2013  West Melbourne (Residential)
3              COMPLETED           2014  West Melbourne (Residential)
4              COMPLETED           2007               North Melbourne
...                  ...            ...                           ...
1169  UNDER CONSTRUCTION           None                       Carlton
1170  UNDER CONSTRUCTION           None                East Melbourne
1171  UNDER CONSTRUCTION           None                     Southbank
1172  UNDER CONSTRUCTION           None                East Melbourne
1173  UNDER CONSTRUCTION           None               North Melbourne

      clue_block property_id  floors_above  resi_dwellings  studio_dwe  \
0            342      100023             2              17           0
1            333      100119             3              12           0
2            414      100144             4               3           0
3            409      100441             3              28           0
4           1012      100556             2               0           0
...          ...         ...           ...             ...         ...
1169         245      107554             7              36           0
1170         620      100361             9              23           0
1171         807      110440            66             372           0
1172         621      100355             9              14           0
1173        2383      616902            12             276           0

      one_bdrm_dwe  two_bdrm_dwe  ...  community_flr  car_spaces  bike_spaces  \
0                0             0  ...              0           0            0
1                0             0  ...              0           0            0
2                0             0  ...              0           0            0
3               17            11  ...              0           0           28
4                0             0  ...              0           0            0
...            ...           ...  ...            ...         ...          ...
1169             0            20  ...              0          56          137
1170             0            12  ...              0          35           25
1171           140           161  ...              0         111          153
1172             0             3  ...              0          58           39
1173           102           169  ...              0         234          225

      census_year                                building_address  \
0            2014  191-201 Abbotsford Street NORTH MELBOURNE 3051
1            2019  218-224 Abbotsford Street NORTH MELBOURNE 3051
2            2019     56-62 Abbotsford Street WEST MELBOURNE 3003
3             NaN                                             NaN
4             NaN                                             NaN
...           ...                                             ...
1169          NaN                                             NaN
1170          NaN                                             NaN
1171          NaN                                             NaN
1172         2014       364-366 Albert Street EAST MELBOURNE 3002
1173          NaN                                             NaN

               dwelling_type  dwelling_number   longitude   latitude  \
0     Residential Apartments             17.0  144.945030 -37.802822
1     Residential Apartments             12.0  144.945947 -37.802049
2     Residential Apartments              3.0  144.944719 -37.806791
3                        NaN              NaN         NaN        NaN
4                        NaN              NaN         NaN        NaN
...                      ...              ...         ...        ...
1169                     NaN              NaN         NaN        NaN
1170                     NaN              NaN         NaN        NaN
1171                     NaN              NaN         NaN        NaN
1172  Residential Apartments              1.0  144.979101 -37.809578
1173                     NaN              NaN         NaN        NaN

                                               location
0     {'lon': 144.94502977479658, 'lat': -37.8028218...
1     {'lon': 144.94594737510627, 'lat': -37.8020493...
2     {'lon': 144.9447185352413, 'lat': -37.80679128...
3                                                   NaN
4                                                   NaN
...                                                 ...
1169                                                NaN
1170                                                NaN
1171                                                NaN
1172  {'lon': 144.9791007248, 'lat': -37.80957772068...
1173                                                NaN

[1174 rows x 38 columns]

### Merge 'Development & Residential' with 'Building information'

In [35]:
list(df_bldg_cleaned)

['census_year',
 'block_id',
 'property_id',
 'street_address',
 'clue_small_area',
 'construction_year',
 'refurbished_year',
 'number_of_floors_above_ground',
 'predominant_space_use',
 'accessibility_type',
 'accessibility_type_description',
 'accessibility_rating',
 'bicycle_spaces',
 'has_showers',
 'longitude',
 'latitude',
 'location']

In [36]:
# skip column 'floors_above' from dataframe 'left_dev_res'

dev_res_exclude = ['floors_above']
left_dev_res = left_dev_res.drop(dev_res_exclude, axis = 1)

# skip columns from 'df_bldg_cleaned':
# 'census_year', 'block_id', 'street_address', 'clue_small_area', 'longitude', 'latitude' and 'location'

bldg_exclude = ['census_year', 'block_id', 'street_address', 'clue_small_area', 'longitude', 'latitude', 'location']
df_bldg_selected = df_bldg_cleaned.drop(bldg_exclude, axis = 1)

In [40]:
# left join

left_dev_res_bldg = pd.merge(left_dev_res, df_bldg_selected, on = 'property_id', how = 'left')

len(left_dev_res_bldg)

1174

In [41]:
list(left_dev_res_bldg.columns)

['status',
 'year_completed',
 'clue_small_area',
 'clue_block',
 'property_id',
 'resi_dwellings',
 'studio_dwe',
 'one_bdrm_dwe',
 'two_bdrm_dwe',
 'three_bdrm_dwe',
 'student_apartments',
 'student_beds',
 'student_accommodation_units',
 'institutional_accom_beds',
 'hotel_rooms',
 'serviced_apartments',
 'hotels_serviced_apartments',
 'hostel_beds',
 'childcare_places',
 'office_flr',
 'retail_flr',
 'industrial_flr',
 'storage_flr',
 'education_flr',
 'hospital_flr',
 'recreation_flr',
 'publicdispaly_flr',
 'community_flr',
 'car_spaces',
 'bike_spaces',
 'census_year',
 'building_address',
 'dwelling_type',
 'dwelling_number',
 'longitude',
 'latitude',
 'location',
 'construction_year',
 'refurbished_year',
 'number_of_floors_above_ground',
 'predominant_space_use',
 'accessibility_type',
 'accessibility_type_description',
 'accessibility_rating',
 'bicycle_spaces',
 'has_showers']

In [42]:
print(left_dev_res_bldg)

                  status year_completed               clue_small_area  \
0              COMPLETED           2006               North Melbourne
1              COMPLETED           2005               North Melbourne
2              COMPLETED           2013  West Melbourne (Residential)
3              COMPLETED           2014  West Melbourne (Residential)
4              COMPLETED           2007               North Melbourne
...                  ...            ...                           ...
1169  UNDER CONSTRUCTION           None                       Carlton
1170  UNDER CONSTRUCTION           None                East Melbourne
1171  UNDER CONSTRUCTION           None                     Southbank
1172  UNDER CONSTRUCTION           None                East Melbourne
1173  UNDER CONSTRUCTION           None               North Melbourne

      clue_block property_id  resi_dwellings  studio_dwe  one_bdrm_dwe  \
0            342      100023              17           0             0
1            333      100119              12           0             0
2            414      100144               3           0             0
3            409      100441              28           0            17
4           1012      100556               0           0             0
...          ...         ...             ...         ...           ...
1169         245      107554              36           0             0
1170         620      100361              23           0             0
1171         807      110440             372           0           140
1172         621      100355              14           0             0
1173        2383      616902             276           0           102

      two_bdrm_dwe  three_bdrm_dwe  ...  \
0                0               0  ...
1                0               0  ...
2                0               3  ...
3               11               0  ...
4                0               0  ...
...            ...             ...  ...
1169            20              16  ...
1170            12              11  ...
1171           161              71  ...
1172             3              11  ...
1173           169               5  ...

                                               location  construction_year  \
0     {'lon': 144.94502977479658, 'lat': -37.8028218...               1890
1     {'lon': 144.94594737510627, 'lat': -37.8020493...               2005
2     {'lon': 144.9447185352413, 'lat': -37.80679128...               1970
3                                                   NaN               1888
4                                                   NaN                NaN
...                                                 ...                ...
1169                                                NaN               1983
1170                                                NaN                NaN
1171                                                NaN                NaN
1172  {'lon': 144.9791007248, 'lat': -37.80957772068...                NaN
1173                                                NaN               1950

      refurbished_year  number_of_floors_above_ground  predominant_space_use  \
0                 None                            2.0  Residential Apartment
1                 None                            3.0  Residential Apartment
2                 None                            1.0              Wholesale
3                 2014                            5.0  Residential Apartment
4                  NaN                            NaN                    NaN
...                ...                            ...                    ...
1169              None                            3.0          Retail - Shop
1170               NaN                            NaN                    NaN
1171               NaN                            NaN                    NaN
1172               NaN                            NaN                    NaN
1173              None                            1.0              Wholesale

                    accessibility_type  \
0      Moderate level of accessibility
1           Low level of accessibility
2     Not determined or not applicable
3     Not determined or not applicable
4                                  NaN
...                                ...
1169        Low level of accessibility
1170                               NaN
1171                               NaN
1172                               NaN
1173       High level of accessibility

                         accessibility_type_description  accessibility_rating  \
0     Main entrance has steps; Alternative entrance ...                     2
1                              All entrances have steps                     1
2     Building is not considered to be publicly acce...                     0
3     Configuration of entrance does not fit into an...                     0
4                                                   NaN                   NaN
...                                                 ...                   ...
1169                           All entrances have steps                     1
1170                                                NaN                   NaN
1171                                                NaN                   NaN
1172                                                NaN                   NaN
1173  Main Entrance is at grade and has no steps or ...                     3

      bicycle_spaces  has_showers
0                0.0         None
1                0.0         None
2                NaN         None
3               28.0         None
4                NaN         None
...              ...          ...
1169             0.0         None
1170             NaN         None
1171             NaN         None
1172             NaN         None
1173             5.0         None

[1174 rows x 46 columns]

# **Data analysis**