# Data science team API teamplate code

Siju Deng

### API request function

In [1]:
import requests
import pandas as pd
import os

def fetch_data(base_url, dataset, api_key, num_records=99, offset=0):
    all_records = []
    max_offset = 9900  # Maximum number of requests

    while True:
        # maximum limit check
        if offset > max_offset:
            break

        # Create API request URL
        filters = f'{dataset}/records?limit={num_records}&offset={offset}'
        url = f'{base_url}{filters}&api_key={api_key}'

        # Start request
        try:
            result = requests.get(url, timeout=10)
            result.raise_for_status()
            records = result.json().get('results')
        except requests.exceptions.RequestException as e:
            raise Exception(f"API request failed: {e}")
        if records is None:
            break
        all_records.extend(records)
        if len(records) < num_records:
            break

        # next cycle offset
        offset += num_records

    # DataFrame all data
    df = pd.DataFrame(all_records)
    return df

API_KEY = os.environ.get('MELBOURNE_API_KEY', input("Please enter your API key: "))
BASE_URL = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/'

Please enter your API key:  a0d28c08580df90345c0c34846cf94b614eb5071d598c3b885237828

In [3]:
# data set name
PRE_COLONIAL_TREES = 'pre-colonial-plant-list'

pre_colonial_trees = fetch_data(BASE_URL, PRE_COLONIAL_TREES, API_KEY)

pre_colonial_trees

,species,common_name_s,certain,beach_and_dunes,saltmarsh,coastal_marshlands_and_brackish_flats,swamp_scrub,woodlands_and_heathlands_on_sand,woodlands_and_forests_on_sedimentary_hills_valleys_and_ridges,grasslands_and_woodlands_on_fertile_plains,cliffs_and_escarpments,river_banks_and_creeklines,wet_heathland,freshwater_wetland,saltwater_wetland,most_likely_occurrence,epbc_category_of_threat,ffg_extinction_risk,ffg_category_of_threat
0,Acacia mucronata var. longifolia,"Narrow-leaf Wattle, Variable Sallow Wattle",NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1.0,None,None,None
1,Acacia pycnantha,Golden Wattle,1.0,0.0,0.0,0.0,1.0,2.1,3.2,3.1,2.1,2.1,0.0,0.0,0,3.2,None,None,None
2,Acacia verticillata var. verticillata,Prickly Moses,NaN,0.0,0.0,0.0,3.1,3.1,0.0,0.0,0.0,3.1,1.0,0.0,0,3.1,None,None,None
3,Acaena echinata,Sheep's Burr,1.0,0.0,0.0,0.0,0.0,1.0,3.1,3.1,3.1,2.1,0.0,0.0,0,3.1,None,None,None
4,Acrotriche prostrata,Trailing Ground-Berry,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,Hovea heterophylla,"Common Hovea, Blue Bonnet, Bird's Eye",NaN,0.0,0.0,0.0,0.0,2.1,3.1,0.0,0.0,0.0,0.0,0.0,0,3.1,None,None,None
1063,Hydrocotyle foveolata,Yellow Pennywort,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1.0,None,None,None
1064,Hydrocotyle muscosa,Mossy Pennywort,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,1.0,None,None,None
1065,Hydrocotyle tripartita,Slender Pennywort,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.1,0.0,1.0,0,2.1,None,None,None
1066,Hydrocotyle verticillata,"Common Pennywort, Shield Pennywort",NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0,1.0,None,None,None

In [4]:
# data set name
CURRENT_TREES = 'trees-with-species-and-dimensions-urban-forest'

current_trees = fetch_data(BASE_URL, CURRENT_TREES, API_KEY)

current_trees

,com_id,common_name,scientific_name,genus,family,diameter_breast_height,year_planted,date_planted,age_description,useful_life_expectency,useful_life_expectency_value,precinct,located_in,uploaddate,coordinatelocation,latitude,longitude,easting,northing,geolocation
0,1546404,River Sheoak,Casuarina cunninghamiana,Casuarina,Casuarinaceae,NaN,2013,2013-01-07,None,None,NaN,None,Park,2021-01-10,"{'lon': 144.97177997020128, 'lat': -37.8180699...",-37.818070,144.971780,321479.34,5812432.31,"{'lon': 144.97177997020128, 'lat': -37.8180699..."
1,1038666,Claret Ash,Fraxinus angustifolia subsp. oxycarpa,Fraxinus,Oleaceae,26.0,1998,1998-11-09,Semi-Mature,11-20 years,20.0,None,Park,2021-01-10,"{'lon': 144.96069216093832, 'lat': -37.7815772...",-37.781577,144.960692,320414.93,5816460.51,"{'lon': 144.96069216093832, 'lat': -37.7815772..."
2,1439845,Kanooka,Tristaniopsis laurina,Tristaniopsis,Myrtaceae,NaN,2009,2009-09-08,None,None,NaN,None,Street,2021-01-10,"{'lon': 144.9455194257097, 'lat': -37.79259845...",-37.792598,144.945519,319105.53,5815208.27,"{'lon': 144.9455194257097, 'lat': -37.79259845..."
3,1070962,Spotted Gum,Corymbia maculata,Corymbia,Myrtaceae,17.0,2007,2007-06-14,Semi-Mature,31-60 years,60.0,None,Street,2021-01-10,"{'lon': 144.9421772126995, 'lat': -37.78013819...",-37.780138,144.942177,318780.78,5816584.46,"{'lon': 144.9421772126995, 'lat': -37.78013819..."
4,1066252,River red gum,Eucalyptus camaldulensis,Eucalyptus,Myrtaceae,19.0,2006,2006-02-20,Semi-Mature,61+ years,80.0,None,Street,2021-01-10,"{'lon': 144.92039340703647, 'lat': -37.7905765...",-37.790577,144.920393,316887.98,5815383.70,"{'lon': 144.92039340703647, 'lat': -37.7905765..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,1287372,Chinaberry Tree,Melia azedarach,Melia,Meliaceae,6.0,2008,2008-06-16,Juvenile,31-60 years,60.0,None,Street,2021-01-10,"{'lon': 144.96185487032108, 'lat': -37.8032135...",-37.803214,144.961855,320569.69,5814061.85,"{'lon': 144.96185487032108, 'lat': -37.8032135..."
9995,1064175,Yellow Box,Eucalyptus melliodora,Eucalyptus,Myrtaceae,NaN,2005,2005-12-29,None,None,NaN,None,Park,2021-01-10,"{'lon': 144.9542655755877, 'lat': -37.78508023...",-37.785080,144.954266,319857.44,5816059.43,"{'lon': 144.9542655755877, 'lat': -37.78508023..."
9996,1068611,Yellow Gum,Eucalyptus leucoxylon,Eucalyptus,Myrtaceae,NaN,2006,2006-10-24,None,None,NaN,None,Park,2021-01-10,"{'lon': 144.94969237020163, 'lat': -37.7774784...",-37.777478,144.949692,319436.19,5816894.14,"{'lon': 144.94969237020163, 'lat': -37.7774784..."
9997,1065473,River red gum,Eucalyptus camaldulensis,Eucalyptus,Myrtaceae,NaN,2006,2006-02-02,None,None,NaN,None,Park,2021-01-10,"{'lon': 144.9520802205775, 'lat': -37.78097001...",-37.780970,144.952080,319654.99,5816511.31,"{'lon': 144.9520802205775, 'lat': -37.78097001..."
9998,1021915,London Plane,Platanus x acerifolia,Platanus,Platanaceae,53.0,1997,1997-11-06,Mature,11-20 years,20.0,None,Street,2021-01-10,"{'lon': 144.96805266082373, 'lat': -37.7961241...",-37.796124,144.968053,321098.27,5814860.42,"{'lon': 144.96805266082373, 'lat': -37.7961241..."

### API csv download two types

In [8]:
# use download link
# Replace 'your_download_link_here' with the actual download link
download_link = 'https://melbournetestbed.opendatasoft.com/api/explore/v2.1/catalog/datasets/on-street-parking-bays/exports/csv?lang=en&timezone=Australia%2FSydney&use_labels=true&delimiter=%2C'

# Read the CSV into a DataFrame
bay_df = pd.read_csv(download_link)

bay_df

,RoadSegmentID,KerbsideID,RoadSegmentDescription,Latitude,Longitude,LastUpdated
0,22730,NaN,Park Street between Mason Street and Randall P...,-37.836245,144.982021,2022-08-31
1,22730,NaN,Park Street between Mason Street and Randall P...,-37.835800,144.982115,2022-08-31
2,20013,5701,Lonsdale Street between William Street and Kin...,-37.814238,144.955451,2023-10-02
3,20013,23444,Lonsdale Street between William Street and Kin...,-37.814271,144.955334,2023-10-02
4,22268,NaN,Clowes Street between Anderson Street and Wals...,-37.830568,144.984713,2022-08-31
...,...,...,...,...,...,...
19157,22492,NaN,Alexandra Avenue between Swan Street Bridge an...,-37.827226,144.980441,2022-08-31
19158,22492,NaN,Alexandra Avenue between Swan Street Bridge an...,-37.827380,144.981004,2022-08-31
19159,22492,NaN,Alexandra Avenue between Swan Street Bridge an...,-37.826361,144.979266,2022-08-31
19160,22492,NaN,Alexandra Avenue between Swan Street Bridge an...,-37.826780,144.979662,2022-08-31
19161,22492,NaN,Alexandra Avenue between Swan Street Bridge an...,-37.825850,144.978719,2022-08-31

In [9]:
# Write by hand
# Replace 'your_download_link_here' with the actual download link
download_link = 'https://melbournetestbed.opendatasoft.com/api/explore/v2.1/catalog/datasets/on-street-parking-bays/exports/csv?delimiter=%3B&list_separator=%2C&quote_all=false&with_bom=true'

# Read the CSV into a DataFrame
bay_df = pd.read_csv(download_link)

bay_df

      roadsegmentid;kerbsideid;roadsegmentdescription;latitude;longitude;lastupdated
0      22730;;Park Street between Mason Street and Ra...
1      22730;;Park Street between Mason Street and Ra...
2      20013;5701;Lonsdale Street between William Str...
3      20013;23444;Lonsdale Street between William St...
4      22268;;Clowes Street between Anderson Street a...
...                                                  ...
19157  22492;;Alexandra Avenue between Swan Street Br...
19158  22492;;Alexandra Avenue between Swan Street Br...
19159  22492;;Alexandra Avenue between Swan Street Br...
19160  22492;;Alexandra Avenue between Swan Street Br...
19161  22492;;Alexandra Avenue between Swan Street Br...

[19162 rows x 1 columns]

### API GeoJSON download

In [11]:
import geopandas as gpd

# API URL of the GeoJSON file
ped_geojson_url = "https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/pedestrian-network/exports/geojson?lang=en&timezone=Australia%2FSydney"
# Read
ped_gdf = gpd.read_file(ped_geojson_url)

ped_gdf

,geo_point_2d,objectid,neworkid,geometry
0,"{'lon': 144.93133591306318, 'lat': -37.7907158...",5749,None,"LINESTRING (144.93153 -37.79074, 144.93152 -37..."
1,"{'lon': 144.92784803634999, 'lat': -37.7905952...",5752,None,"LINESTRING (144.92790 -37.79060, 144.92780 -37..."
2,"{'lon': 144.92777658685, 'lat': -37.7901496101}",5753,None,"LINESTRING (144.92778 -37.79019, 144.92777 -37..."
3,"{'lon': 144.92293792754998, 'lat': -37.7892900...",5762,None,"LINESTRING (144.92294 -37.78929, 144.92294 -37..."
4,"{'lon': 144.9226955825, 'lat': -37.78944639879...",5764,None,"LINESTRING (144.92285 -37.78935, 144.92254 -37..."
...,...,...,...,...
85321,"{'lon': 144.9863268138, 'lat': -37.8336326444}",9981,110188,POINT (144.98633 -37.83363)
85322,"{'lon': 144.9184620511, 'lat': -37.7950035101}",9985,111231,POINT (144.91846 -37.79500)
85323,"{'lon': 144.9573721933, 'lat': -37.7968924371}",9993,108445,POINT (144.95737 -37.79689)
85324,"{'lon': 144.9226949664, 'lat': -37.7967435061}",9998,111354,POINT (144.92269 -37.79674)
85325,"{'lon': 144.96165035, 'lat': -37.8119092124}",10000,103200,POINT (144.96165 -37.81191)