In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("/Users/jasmithavenna/d2i---melbourne-city_2020t3/T3_2020/Pedestrian_count_dataset_with_sensor_location.csv")
df

,date,sensor_description,latitude,longitude,Total_Pedestrian_Count,day
0,2015-02-17,Bourke Street Mall (North),-37.813494,144.965153,23306,Tuesday
1,2015-02-18,Bourke Street Mall (North),-37.813494,144.965153,25683,Wednesday
2,2015-02-19,Bourke Street Mall (North),-37.813494,144.965153,29870,Thursday
3,2015-02-20,Bourke Street Mall (North),-37.813494,144.965153,33726,Friday
4,2015-02-21,Bourke Street Mall (North),-37.813494,144.965153,36076,Saturday
...,...,...,...,...,...,...
98662,2020-10-27,Westwood Place,-37.812358,144.971370,493,Tuesday
98663,2020-10-28,Westwood Place,-37.812358,144.971370,657,Wednesday
98664,2020-10-29,Westwood Place,-37.812358,144.971370,387,Thursday
98665,2020-10-30,Westwood Place,-37.812358,144.971370,443,Friday
98666,2020-10-31,Westwood Place,-37.812358,144.971370,358,Saturday

In [6]:
df_ped = df[df['date'] > '2018-12-31']
df_ped

,date,sensor_description,latitude,longitude,Total_Pedestrian_Count,day
1414,2019-01-01,Bourke Street Mall (North),-37.813494,144.965153,26865,Tuesday
1415,2019-01-02,Bourke Street Mall (North),-37.813494,144.965153,33517,Wednesday
1416,2019-01-03,Bourke Street Mall (North),-37.813494,144.965153,35470,Thursday
1417,2019-01-04,Bourke Street Mall (North),-37.813494,144.965153,22161,Friday
1418,2019-01-05,Bourke Street Mall (North),-37.813494,144.965153,31611,Saturday
...,...,...,...,...,...,...
98662,2020-10-27,Westwood Place,-37.812358,144.971370,493,Tuesday
98663,2020-10-28,Westwood Place,-37.812358,144.971370,657,Wednesday
98664,2020-10-29,Westwood Place,-37.812358,144.971370,387,Thursday
98665,2020-10-30,Westwood Place,-37.812358,144.971370,443,Friday
98666,2020-10-31,Westwood Place,-37.812358,144.971370,358,Saturday

In [17]:
df_ped.to_csv("/Users/jasmithavenna/d2i---melbourne-city_2020t3/T3_2020/Pedestrian_dataset_from_2019.csv")